---
- uid: 'insee/etablissements'
  position: 105
  path: '/v3/insee/sirene/etablissements/{siret}'
  ping_url: 'https://entreprise.api.gouv.fr/ping/insee/sirene'
  perimeter:
    entity_type_description: |+
      **Cette API concerne les √©tablissements inscrits au r√©pertoire Sirene** :
      - ‚úÖ **les √©tablissements des personnes morales de droit priveÃÅ** : les entreprises et les entrepreneurs individuels, dont toutes celles et ceux immatriculeÃÅs au registre du commerce et des socieÃÅteÃÅs (RCS) et/ou au reÃÅpertoire des meÃÅtiers (RM) ;
      - ‚úÖ **les √©tablissements des associations ayant un num√©ro de SIRET** d√©livr√© lorsqu'elles :
        * emploient du personnel salari√© ;
        * sont soumises √† la TVA ;
        * ont demand√© ou b√©n√©ficient de transferts financiers publics.
      - ‚úÖ **les √©tablissements des personnes morales de droit public** : les institutions et services de l'EÃÅtat et les collectiviteÃÅs territoriales ;
      - ‚úÖ **Les √©tablissements des organismes publics ou priv√©s et les entreprises √©trang√®res** qui ont une repr√©sentation ou une activit√© en France.
      - ‚úÖ **Les √©tablissements des loueurs de meubl√©s non professionnels (LMNP) et les particuliers employeurs** (depuis 2022), √† l'exception des cas mentionn√©s au [2¬∞ de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'√™tre inscrits au r√©pertoire Sirene. Cette modification intervient suite au [D√©cret n¬∞ 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.
      - ‚ùå Les √©tablissements de gestion de paye de la fonction publique, bien que pr√©sents dans la base Sirene, ne sont pas concern√©s par cette API. Ils ont √©t√© immatricul√©s pour les seuls besoins de certaines administrations (les imp√¥ts, les URSSAF, la DGCP ‚Ä¶).
      Leur diffusion √† d'autres administrations n'est donc pas pr√©vue.

    geographical_scope_description: &insee_etablissements_geographical_scope_description |+
      La base Sirene concerne les √©tablissements implanteÃÅs en meÃÅtropole, dans les DROM et dans les collectiviteÃÅs d'Outre-Mer de Saint-Pierre-et-Miquelon, Saint-BartheÃÅleÃÅmy et Saint-Martin.

      ‚ö†Ô∏è Pour la Nouvelle-Cal√©donie, la Polyn√©sie fran√ßaise, et Wallis-et-Futuna, seul le secteur public administratif, de l'√âtat ou des communes est r√©pertori√© ;
      ‚ùå les entreprises ne sont donc pas disponibles.
    updating_rules_description: &insee_etablissements_updating_rules_description |+
      La mise √† jour des donn√©es est faite **quotidiennement entre 0h et 3h** √† l'Insee.
    know_more_description: &insee_etablissements_know_more_description |+
      L'[article R123-220 du Code du commerce](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904){:target="_blank"} liste les entit√©s tenues d'√™tre inclues dans le r√©pertoire Sirene par l'Insee.

      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [‚úíÔ∏è **Inciter vos usagers √† mettre √† jour leurs informations dans le r√©pertoire Sirene** - Lire la publication du 02/06/2023](https://entreprise.api.gouv.fr/blog/references-sites-modification-donnees)
    entities:
    - entreprises
    - associations
  opening: protected
  call_id: &insee_etablissements_call_id SIRET
  parameters: &insee_etablissements_parameters
    - Num√©ro de SIRET de l'√©tablissement
  format: &insee_etablissements_format
    - Donn√©e structur√©e JSON
  provider_uids: &insee_etablissements_provider_uids
    - 'insee'
  keywords: &insee_etablissements_keywords
    - 'activit√©'
    - 'naf'
    - 'ape'
    - 'identit√©'
    - 'identification'
    - '√©tat'
    - 'effectif'
    - 'raison sociale'
    - 'nom'
    - 'num√©ro tva'
    - 'forme juridique'
    - 'localisation'
    - 'emplacement'
    - 'adresse'
    - 'commune'
    - 'r√©gion'
    - 'pays'
    - 'cedex'
    - 'cessation'
    - 'cessation'
    - 'cl√¥ture'
    - 'remplissage'
    - 'fraude'
    - 'aides'
    - 'march√©s'
    - 'ess'
    - '√©conomie sociale et solidaire'
  data:
    description: |+
      √Ä partir du num√©ro de SIRET de l'√©tablissement, cette API d√©livre les **informations g√©n√©rales de celui-ci** et les **informations g√©n√©rales de l'unit√© l√©gale** √† laquelle l'√©tablissement est rattach√©. 
      
      {:.fr-highlight.fr-highlight--caution}
      > ‚ö†Ô∏è **Cette API d√©livre des informations prot√©g√©es**
      > **Pour faire du pr√©-remplissage dans un formulaire public**, nous vous recommandons d'utiliser l'[API d√©livrant uniquement de la donn√©e publique](<%= endpoint_path(uid: 'insee/etablissements_diffusibles')%>).
      Pour en savoir plus sur la fa√ßon d'utiliser les donn√©es du million d'√©tablissements "en diffusion partielle", essentiellement des entreprises individuelles, consultez [cette rubrique](#utilisation-diffusion-partielle).
  faq:
    - q: &insee_etablissements_faq_q1 √Ä quoi correspondent les √©tats administratifs ? Une unit√© l√©gale peut-elle √™tre en activit√© alors que tous ses √©tablissements sont ferm√©s ?
      a: &insee_etablissements_faq_a1 |+
        √Ä gros trait, l'√©tat administratif vous permet de v√©rifier si l'entreprise ou l'association est en activit√©. Il faut pour cela distinguer et v√©rifier l'√©tat administratif de l'unit√© l√©gale et celui de ses √©tablissments.

        **√âtat administratif de l'unit√© l√©gale&nbsp;:**
        L'√©tat administratif de l'unit√© l√©gale peut √™tre "actif" ou "cess√©".
        L'unit√© l√©gale est toujours active, sauf si une d√©claration de cessation administrative a √©t√© d√©pos√©e et prise en compte par l'Insee.
        L'√©tat administratif indique si une unit√© l√©gale est active ou cess√©e.

        **√âtat administratif d'un √©tablissement&nbsp;:**
        Il peut √™tre "actif" ou "ferm√©". Lors de son inscription au reÃÅpertoire Sirene, un eÃÅtablissement est, sauf exception, aÃÄ l'eÃÅtat "actif". Le passage aÃÄ l'eÃÅtat "ferm√©" deÃÅcoule de la prise en compte d'une deÃÅclaration de fermeture. Un eÃÅtablissement fermeÃÅ peut eÃÇtre rouvert.

        **Cas particuliers&nbsp;:**
        - **une unit√© l√©gale est active alors que tous ses √©tablissements sont ferm√©s**. Il s'agit alors d'une entit√© active d'un point de vue administratif mais n'ayant pas d'activit√© √©conomique. Cette situation regroupe :
           - Les soci√©t√©s en sommeil, c'est-√†-dire faire reconna√Ætre par une formalit√© leur √©tat en sommeil afin de ne plus avoir certaines obligations fiscales ;
           - Les soci√©t√©s pr√©sum√©es inactives, identifi√©es par l‚ÄôInsee pour des besoins statistiques.

           La distinction "en sommeil" ou "pr√©sum√©e inactive" n'est pas une information transmise par l'Insee.
        - **une unit√© l√©gale est cess√©e alors qu'un √©tablissement est actif**. Cette situation est une erreur √† signaler au p√¥le du r√©pertoire Sirene √† l'Insee. Une unit√© l√©gale cess√©e ne peut avoir d'√©tablissements actifs.

    - q: &insee_etablissements_faq_q2 <a name="definition-diffusion-partielle"></a>Qu'est-ce qu'un √©tablissement "en diffusion partielle" ?
      a: &insee_etablissements_faq_a2 |+
        **La diffusion partielle commerciale :**

        Parmi les entit√©s pr√©sentes dans le r√©pertoire Sirene, certaines, tr√®s majoritairement des personnes physiques, ont explicitement demand√© de ne pas figurer en diffusion totale, afin de ne pas rendre publiques leurs donn√©es d'identification et de localisation. L'Insee √©value leur nombre a plus d'un million d'√©tablissements (chiffre 2025), essentiellement des entreprises individuelles.

        Ce [droit d'opposition tel que d√©crit √† l'Article 21 du RGPD](https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre3#Article21){:target="_blank"} est valable pour les personnes physiques et morales mais s'applique de fa√ßon diff√©rente : 
        - pour les personnes morale, seuls les √©l√©ments de localisation sont prot√©g√©s (g√©olocalisation, num√©ro et voie de l'adresse postale - la commune reste diffusible) ; 
        - pour les personnes physiques, les √©l√©ments de localisation pr√©c√©dents sont prot√©g√©s, ainsi que les √©l√©ments d'identification (nom, pr√©nom, pseudonyme).

        **Ces donn√©es prot√©g√©es sont alors uniquement accessibles √† des organismes habilit√©s et √† des administrations.** Elles sont disponibles dans l'API Entreprise.

        {:.fr-highlight}
        > Le statut de diffusion partielle est nouveau, il est venu remplacer le statut ‚Äúnon-diffusible‚Äù en 2023. Ce nouveau statut rend public plus d'informations, dont, pour les personnes physiques, le SIREN, SIRET, la commune et le pays, ainsi que l'√©tat administratif et les variables √©conomiques. Il a √©largi la possibilit√© de la diffusion partielle aux personnes morales, pour leur permettre de cacher leurs donn√©es de localisation.<br>Lire notre publication du 14/12/2022 : [ü¶∏&nbsp;**Le futur des ‚Äúnon-diffusibles‚Äù**](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles).


        **La non-diffusion totale disponibles pour des cas sp√©cifiques :**
        Certaines entit√©s ne sont pas diffusibles pour d'autres raisons que la non-diffusion commerciale. C'est par exemple le cas :
        - des √©tablissements de gestion de paye de la fonction publique immatricul√©s pour les seuls besoins de certaines administrations (les imp√¥ts, les URSSAF, la DGCP ‚Ä¶) et donc uniquement accessibles √† ces administrations fiscales.
        - des unit√©s de la D√©fense nationale, accessibles sur autorisation du Minist√®re de la D√©fense, conform√©ment √† l‚Äô[article A 123-95 du Code du commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000020165032/2010-07-02){:target="_blank"}. **Ces unit√©s ne sont pas diffus√©es par l'API Entreprise**.

    - q: &insee_etablissements_faq_q3 <a name="utilisation-diffusion-partielle"></a>Comment utiliser les informations des √©tablissements "en diffusion partielle" ?
      a: |+
        En utilisant cette API, vous vous engagez √† **tenir compte du statut de diffusion le plus r√©cent** de l'entit√© appel√©e.
        Dans le cas o√π l'entit√© est indiqu√©e comme \"en diffusion partielle\", vous vous engagez √† n'utiliser leurs informations prot√©g√©es que dans le cadre strict de vos missions de service public, √† ne pas les rediffuser ni les divulguer aupr√®s de tiers non autoris√©s.

        {:.fr-highlight.fr-highlight--caution}
        > ‚ö†Ô∏è **Vous ne pouvez pas donc pas faire usage des donn√©es prot√©g√©es d'une entit√© "en diffusion partielle" pour du pr√©remplissage.** Seules les donn√©es diffusibles peuvent √™tre utilis√©es pour du pr√©remplissage, c'est-√†-dire : le SIREN, SIRET, la commune et le pays, ainsi que l'√©tat administratif et les variables √©conomiques.
        > Pour faire du pr√©-remplissage dans un formulaire public, nous vous recommandons d'utiliser l'[API d√©livrant uniquement de la donn√©e publique](<%= endpoint_path(uid: 'insee/etablissements_diffusibles') %>) pour ne pas faire d'erreur.

        {:.fr-highlight}
        > **Depuis 2023, les personnes morales sont concern√©es par la \"diffusion partielle\"**. Si elles ont exerc√© ce droit, vous n'avez pas le droit de pr√©-remplir leur donn√©es de localisation : g√©olocalisation, num√©ro et voie de l'adresse postale. La commune reste diffusible.

- uid: 'insee/etablissements_diffusibles'
  position: 100
  ping_url: 'https://entreprise.api.gouv.fr/ping/insee/sirene'
  path: '/v3/insee/sirene/etablissements/diffusibles/{siret}'
  perimeter:
    entity_type_description: |+
      **Cette API concerne les √©tablissements inscrits au r√©pertoire Sirene** :
      - ‚úÖ **les √©tablissements des personnes morales de droit priveÃÅ** : les entreprises et les entrepreneurs individuels, dont toutes celles et ceux immatriculeÃÅs au registre du commerce et des socieÃÅteÃÅs (RCS) et/ou au reÃÅpertoire des meÃÅtiers (RM) ;
      - ‚úÖ **les √©tablissements des associations ayant un num√©ro de SIRET** d√©livr√© lorsqu'elles :
        * emploient du personnel salari√© ;
        * sont soumises √† la TVA ;
        * ont demand√© ou b√©n√©ficient de transferts financiers publics.
      - ‚úÖ **les √©tablissements des personnes morales de droit public** : les institutions et services de l'EÃÅtat et les collectiviteÃÅs territoriales ;
      - ‚úÖ **Les √©tablissements des organismes publics ou priv√©s et les entreprises √©trang√®res** qui ont une repr√©sentation ou une activit√© en France.
      - ‚úÖ **Les √©tablissements des loueurs de meubl√©s non professionnels (LMNP) et les particuliers employeurs** (depuis 2022), √† l'exception des cas mentionn√©s au [2¬∞ de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'√™tre inscrits au r√©pertoire Sirene. Cette modification intervient suite au [D√©cret n¬∞ 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.

      {:.fr-highlight}
      > üí° **Seules des donn√©es publiques sont disponibles avec cette API**. 
      > Pour obtenir les donn√©es prot√©g√©es du million d'√©tablissements ["en diffusion partielle"](#definition-diffusion-partielle), essentiellement des entreprises individuelles, veuillez utiliser [cette API](<%= endpoint_path(uid: 'insee/etablissements') %>).

    geographical_scope_description: *insee_etablissements_geographical_scope_description
    updating_rules_description: *insee_etablissements_updating_rules_description
    know_more_description: *insee_etablissements_know_more_description
    entities:
    - entreprises
    - associations
  opening: public
  format: *insee_etablissements_format
  parameters: *insee_etablissements_parameters
  call_id: *insee_etablissements_call_id
  provider_uids: *insee_etablissements_provider_uids
  keywords: *insee_etablissements_keywords
  data:
    description: |+
      √Ä partir du num√©ro de SIRET de l'√©tablissement, cette API d√©livre les **informations g√©n√©rales de celui-ci** et les **informations g√©n√©rales de l'unit√© l√©gale** √† laquelle l'√©tablissement est rattach√©. 
      
      **Cette API d√©livre uniquement des donn√©es publiques**. Pour obtenir les donn√©es prot√©g√©es du million d'√©tablissements en ["diffusion partielle"](#definition-diffusion-partielle), essentiellement des entreprises individuelles, utilisez [cette API](<%= endpoint_path(uid: 'insee/etablissements') %>).
  faq:
    - q: *insee_etablissements_faq_q1
      a: *insee_etablissements_faq_a1
    - q: *insee_etablissements_faq_q2
      a: *insee_etablissements_faq_a2
    - q: *insee_etablissements_faq_q3
      a: |+
        Cette API d√©livre uniquement des donn√©es **publiques**. Par cons√©quent, vous pouvez utiliser les donn√©es disponibles dans tous vos services, qu'ils soient accessibles avec ou sans authentification.
        
        Pour obtenir les donn√©es prot√©g√©es du million d'√©tablissements en "diffusion partielle", essentiellement des entreprises individuelles, utilisez [cette API](<%= endpoint_path(uid: 'insee/etablissements') %>).
