---
- uid: 'insee/etablissements'
  position: 105
  path: '/v3/insee/sirene/etablissements/{siret}'
  ping_url: 'https://entreprise.api.gouv.fr/ping/insee/sirene'
  perimeter:
    entity_type_description: &insee_etablissements_entity_type_description |+
      Cette API concerne les Ã©tablissements inscrits au rÃ©pertoire Sirene, qu'ils soient **"diffusibles" ou ["non-diffusibles"](#faq_entry_1_endpoint_insee_etablissements)** :

      - âœ… les Ã©tablissements des personnes morales de droit priveÌ : **les entreprises et les entrepreneurs individuels**, dont toutes celles et ceux immatriculeÌs au registre du commerce et des socieÌteÌs (RCS) et/ou au reÌpertoire des meÌtiers (RM).
      - âœ… les Ã©tablissements des **associations ayant un numÃ©ro de SIRET**, dÃ©livrÃ© lorsqu'elles :
        * emploient du personnel salariÃ© ;
        * sont soumises Ã  la TVA ;
        * ont demandÃ© ou bÃ©nÃ©ficient de transferts financiers publics.
      - âœ… les Ã©tablissements des personnes morales de droit public : les **institutions et services de l'EÌtat** et les collectiviteÌs territoriales ;
      - âœ… Les Ã©tablissements des organismes publics ou privÃ©s et les entreprises Ã©trangÃ¨res qui ont une reprÃ©sentation ou une activitÃ© en France.


      {:.fr-highlight}
      âœ… Depuis janvier 2022, les loueurs de meublÃ©s non professionnels (LMNP) et les particuliers employeurs, Ã  l'exception des cas mentionnÃ©s au [2Â° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'Ãªtre inscrits au rÃ©pertoire Sirene. Cette modification intervient suite au [DÃ©cret nÂ° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.


      âŒ Les Ã©tablissements de gestion de paye de la fonction publique, bien que prÃ©sents dans la base Sirene, ne sont pas concernÃ©s par cette API. Ils ont Ã©tÃ© immatriculÃ©s pour les seuls besoins de certaines administrations (les impÃ´ts, les URSSAF, la DGCP â€¦).
      Leur diffusion Ã  d'autres administrations n'est donc pas prÃ©vue.

    geographical_scope_description: &insee_etablissements_geographical_scope_description |+
      La base Sirene concerne les Ã©tablissements implanteÌs en meÌtropole, dans les DROM et dans les collectiviteÌs d'Outre-Mer de Saint-Pierre-et-Miquelon, Saint-BartheÌleÌmy et Saint-Martin.

      âš ï¸ Pour la Nouvelle-CalÃ©donie, la PolynÃ©sie franÃ§aise, et Wallis-et-Futuna, seul le secteur public administratif, de l'Ã‰tat ou des communes est rÃ©pertoriÃ© ;
      âŒ les entreprises ne sont donc pas disponibles.
    updating_rules_description: &insee_etablissements_updating_rules_description |+
      La mise Ã  jour des donnÃ©es est faite **quotidiennement entre 0h et 3h** Ã  l'Insee.
    know_more_description: &insee_etablissements_know_more_description |+
      L'[article R123-220 du Code du commerce](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904){:target="_blank"} liste les entitÃ©s tenues d'Ãªtre inclues dans le rÃ©pertoire Sirene par l'Insee.

      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [ğŸ¦¸ **Le futur des â€œnon-diffusiblesâ€** - Lire la publication du 14/12/2022](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles)

      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [âœ’ï¸ **Inciter vos usagers Ã  mettre Ã  jour leurs informations dans le rÃ©pertoire Sirene** - Lire la publication du 02/06/2023](https://entreprise.api.gouv.fr/blog/references-sites-modification-donnees)
    entities:
    - entreprises
    - associations
  opening: protected
  call_id: &insee_etablissements_call_id SIRET
  parameters: &insee_etablissements_parameters
    - NumÃ©ro de SIRET de l'Ã©tablissement
  format: &insee_etablissements_format
    - DonnÃ©e structurÃ©e JSON
  use_cases:
    - MarchÃ©s publics
    - Aides publiques
    - DÃ©tection de la fraude
    - Portail GRU - Instruction des dÃ©marches
    - Subventions associations
  use_cases_forbidden:
    - Portail GRU - PrÃ©remplissage
  provider_uids: &insee_etablissements_provider_uids
    - 'insee'
  keywords: &insee_etablissements_keywords
    - 'activitÃ©'
    - 'naf'
    - 'ape'
    - 'identitÃ©'
    - 'identification'
    - 'Ã©tat'
    - 'effectif'
    - 'raison sociale'
    - 'nom'
    - 'numÃ©ro tva'
    - 'forme juridique'
    - 'localisation'
    - 'emplacement'
    - 'adresse'
    - 'commune'
    - 'rÃ©gion'
    - 'pays'
    - 'cedex'
    - 'cessation'
    - 'cessation'
    - 'clÃ´ture'
    - 'remplissage'
    - 'fraude'
    - 'aides'
    - 'marchÃ©s'
    - 'ess'
    - 'Ã©conomie sociale et solidaire'
  data:
    description: &insee_etablissement_data_description |+
      Ã€ partir du numÃ©ro de SIRET de l'Ã©tablissement, cette API dÃ©livre les **informations gÃ©nÃ©rales de celui-ci** et les **informations gÃ©nÃ©rales de l'unitÃ© lÃ©gale** Ã  laquelle l'Ã©tablissement est rattachÃ©.
  faq:
    - q: &insee_etablissements_faq_q1 Ã€ quoi correspondent les Ã©tats administratifs ? Une unitÃ© lÃ©gale peut-elle Ãªtre en activitÃ© alors que tous ses Ã©tablissements sont fermÃ©s ?
      a: &insee_etablissements_faq_a1 |+
        Ã€ gros trait, l'Ã©tat administratif vous permet de vÃ©rifier si l'entreprise ou l'association est en activitÃ©. Il faut pour cela distinguer et vÃ©rifier l'Ã©tat administratif de l'unitÃ© lÃ©gale et celui de ses Ã©tablissments.

        **Ã‰tat administratif de l'unitÃ© lÃ©gale&nbsp;:**
        L'Ã©tat administratif de l'unitÃ© lÃ©gale peut Ãªtre "actif" ou "cessÃ©".
        L'unitÃ© lÃ©gale est toujours active, sauf si une dÃ©claration de cessation administrative a Ã©tÃ© dÃ©posÃ©e et prise en compte par l'Insee.
        L'Ã©tat administratif indique si une unitÃ© lÃ©gale est active ou cessÃ©e.

        **Ã‰tat administratif d'un Ã©tablissement&nbsp;:**
        Il peut Ãªtre "actif" ou "fermÃ©". Lors de son inscription au reÌpertoire Sirene, un eÌtablissement est, sauf exception, aÌ€ l'eÌtat "actif". Le passage aÌ€ l'eÌtat "fermÃ©" deÌcoule de la prise en compte d'une deÌclaration de fermeture. Un eÌtablissement fermeÌ peut eÌ‚tre rouvert.

        **Cas particuliers&nbsp;:**
        - **une unitÃ© lÃ©gale est active alors que tous ses Ã©tablissements sont fermÃ©s**. Il s'agit alors d'une entitÃ© active d'un point de vue administratif mais n'ayant pas d'activitÃ© Ã©conomique. Cette situation regroupe :
           - Les sociÃ©tÃ©s en sommeil, c'est-Ã -dire faire reconnaÃ®tre par une formalitÃ© leur Ã©tat en sommeil afin de ne plus avoir certaines obligations fiscales ;
           - Les sociÃ©tÃ©s prÃ©sumÃ©es inactives, identifiÃ©es par lâ€™Insee pour des besoins statistiques.

           La distinction "en sommeil" ou "prÃ©sumÃ©e inactive" n'est pas une information transmise par l'Insee.
        - **une unitÃ© lÃ©gale est cessÃ©e alors qu'un Ã©tablissement est actif**. Cette situation est une erreur Ã  signaler au pÃ´le du rÃ©pertoire Sirene Ã  l'Insee. Une unitÃ© lÃ©gale cessÃ©e ne peut avoir d'Ã©tablissements actifs.

    - q: &insee_etablissements_faq_q2 Qu'est-ce qu'un "non-diffusible" ?
      a: &insee_etablissements_faq_a2 |+

        **La non-diffusion commerciale :**
        Parmi les entitÃ©s prÃ©sentes dans le rÃ©pertoire Sirene, certaines, trÃ¨s majoritairement des personnes physiques, ont explicitement demandÃ© de ne pas figurer en diffusion commerciale, en vertu de l'[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/){:target="_blank"}.

        Cela signifie qu'elles donnent accord de la diffusion de leur donnÃ©es uniquement Ã  des organismes habilitÃ©s et Ã  des administrations. **De fait, leurs donnÃ©es ne sont pas publiques**.

        {:.fr-highlight}
        > Ã€ partir de mars 2024, le fonctionnement des non-diffusibles commerciaux Ã©volue, certaines donnÃ©es seront disponibles pour du prÃ©-remplissage et les personnes morales pourront dÃ©cider de passer en diffusion partielle. <br>Lire notre publication du 14/12/2022 : [ğŸ¦¸&nbsp;**Le futur des â€œnon-diffusiblesâ€**](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles).


        **La non-diffusion pour d'autres raisons :**
        Certaines entitÃ©s ne sont pas diffusibles pour d'autres raisons que la non-diffusion commerciale. C'est par exemple le cas :
        - des Ã©tablissements de gestion de paye de la fonction publique immatriculÃ©s pour les seuls besoins de certaines administrations (les impÃ´ts, les URSSAF, la DGCP â€¦) et donc uniquement accessibles Ã  ces administrations fiscales.
        - des unitÃ©s de la DÃ©fense nationale, accessibles sur autorisation du MinistÃ¨re de la DÃ©fense, conformÃ©ment Ã  lâ€™[article A 123-95 du Code du commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000020165032/2010-07-02){:target="_blank"}. **Ces unitÃ©s ne sont pas diffusÃ©es par l'API Entreprise**.



    - q: &insee_etablissements_faq_q3 Comment utiliser les informations des Ã©tablissements "non-diffusibles" ?
      a: &insee_etablissements_faq_a3 |+
        En utilisant cette API, vous vous engagez Ã  **tenir compte du statut de diffusion le plus rÃ©cent** de l'entitÃ© appelÃ©e.
        Dans le cas oÃ¹ l'entitÃ© est indiquÃ©e comme \"non-diffusible\", vous vous engagez Ã  n'utiliser leurs informations que dans le cadre strict de vos missions de service public, Ã  ne pas les rediffuser ni les divulguer auprÃ¨s de tiers non autorisÃ©s.

        {:.fr-highlight.fr-highlight--caution}
        > âš ï¸ **Vous ne pouvez pas donc pas faire usage des donnÃ©es d'une entitÃ© "non-diffusible" pour du prÃ©remplissage.**

        {:.fr-highlight}
        > Il vous est par contre possible d'indiquer Ã  l'entitÃ© "non-diffusible" qu'elle peut modifier son statut, mÃªme provisoirement, auprÃ¨s de l'Insee Ã  l'adresse suivante : [https://statut-diffusion-sirene.insee.fr](https://statut-diffusion-sirene.insee.fr){:target="_blank"}.

        Ã€ partir de mars 2024, le fonctionnement des non-diffusibles commerciaux Ã©volue, certaines donnÃ©es seront disponibles pour du prÃ©-remplissage et les personnes morales pourront dÃ©cider de passer en diffusion partielle. Lire notre publication du 14/12/2022 : [ğŸ¦¸&nbsp;**Le futur des â€œnon-diffusiblesâ€**](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles).

- uid: 'insee/etablissements_diffusibles'
  position: 100
  ping_url: 'https://entreprise.api.gouv.fr/ping/insee/sirene'
  path: '/v3/insee/sirene/etablissements/diffusibles/{siret}'
  perimeter:
    entity_type_description: |+
      Cette API concerne les Ã©tablissements inscrits au rÃ©pertoire Sirene et "diffusibles" commercialement  :
      - âœ… les Ã©tablissements des personnes morales de droit priveÌ : **les entreprises et les entrepreneurs individuels**, dont toutes celles et ceux immatriculeÌs au registre du commerce et des socieÌteÌs (RCS) et/ou au reÌpertoire des meÌtiers (RM) ;
      - âœ… les Ã©tablissements des personnes morales de droit public : les **institutions et services de l'EÌtat** et les collectiviteÌs territoriales ;
      - âœ… les Ã©tablissements des **associations ayant un numÃ©ro de SIRET** dÃ©livrÃ© lorsqu'elles :
        * emploient du personnel salariÃ© ;
        * sont soumises Ã  la TVA ;
        * ont demandÃ© ou bÃ©nÃ©ficient de transferts financiers publics.
      - âœ… Les Ã©tablissements des organismes publics ou privÃ©s et les entreprises Ã©trangÃ¨res qui ont une reprÃ©sentation ou une activitÃ© en France.


      {:.fr-highlight}
      âœ… Depuis janvier 2022, les loueurs de meublÃ©s non professionnels (LMNP) et les particuliers employeurs, Ã  l'exception des cas mentionnÃ©s au [2Â° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'Ãªtre inscrits au rÃ©pertoire Sirene. Cette modification intervient suite au [DÃ©cret nÂ° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.

      âŒ **Les Ã©tablissements ["non-diffusibles"](#faq_entry_1_endpoint_insee_etablissements_diffusibles) ne sont pas couverts par cette API**, leurs informations sont appelables avec [cette API](<%= endpoint_path(uid: 'insee/etablissements') %>).

    geographical_scope_description: *insee_etablissements_geographical_scope_description
    updating_rules_description: *insee_etablissements_updating_rules_description
    know_more_description: *insee_etablissements_know_more_description
    entities:
    - entreprises
    - associations
  opening: public
  use_cases_optional:
    - DÃ©tection de la fraude
  use_cases:
    - Portail GRU - PrÃ©remplissage
    - Portail GRU - Instruction des dÃ©marches
    - MarchÃ©s publics
    - Aides publiques
    - Subventions associations
  format: *insee_etablissements_format
  parameters: *insee_etablissements_parameters
  call_id: *insee_etablissements_call_id
  provider_uids: *insee_etablissements_provider_uids
  keywords: *insee_etablissements_keywords
  data:
    description: *insee_etablissement_data_description
  faq:
    - q: *insee_etablissements_faq_q1
      a: *insee_etablissements_faq_a1
    - q: *insee_etablissements_faq_q2
      a: *insee_etablissements_faq_a2
    - q: *insee_etablissements_faq_q3
      a: *insee_etablissements_faq_a3
