---
- uid: 'dgfip/liasses_fiscales'
  path: '/v3/dgfip/unites_legales/{siren}/liasses_fiscales/{year}'
  position: 240
  perimeter:
    entity_type_description: |+
      Cette API délivre les liasses fiscales des entreprises :
      - ✅ soumises à l’impôt sur les sociétés (IS)* ;
      - ✅ soumises à l’impôt sur les sociétés dû par le groupe (IS GROUPE)*;
      - ✅ aux bénéfices industriels et commerciaux (BIC)* ;
      - ✅ aux bénéfices non commerciaux (BNC)* ;
      - ✅ aux bénéfices agricoles (BA)*.

      _*selon les règles des régimes réels, normal ou simplifié._

      ❌ Les entreprises aux régimes micro-BIC, micro-BNC et micro-BA (micro-entrepreneurs) ne sont pas concernées par cette API. En effet, elles ne déposent pas de déclarations de résultat mais des éléments spécifiques dans la déclaration 2042C qui relève de l’impôt sur le revenu.



    updating_rules_description: |+
      Les déclarations de résultat sont disponibles **à compter du lendemain de la date de dépôt (J+1) et trois jours plus tard (J+3)** si le dépôt intervient une veille de week-end.

      La date limite de dépôt des déclarations de résultat est fixée au 2ème jour ouvré après le 1er mai pour les entreprises qui clôturent à la fin de l’année civile.

      En cas d’exercice à cheval, la date limite de dépôt est positionnée exactement trois mois après la date de clôture de l’exercice déclaré.
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'dgfip'
  data:
    description: |+
      Cette API délivre les liasses fiscales d'une entreprise pour l'année renseignée. Pour chaque liasse fiscale, les informations suivantes sont transmises :
      - Les règles d'imposition applicables à l'entreprise ;
      - Des informations sur le formulaire complêté par l'entreprise, à l'origine des données transmises ;
      - Les données de la déclaration.
  opening: protected
  use_cases:
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: Comment distinguer l'imprimé rectificatif de l'initial ?
      a: |+
        Pour un même exercice, il y a parfois plusieurs fois le même imprimé : il s'agit de corrections qui ont été apportées par une déclaration ultérieure.

        Les déclarations dans la réponse JSON de l'API sont alors triées de l'imprimé le plus récent au plus ancien. Ainsi **le premier imprimé est toujours le plus récent**.
        
        
        {:.fr-highlight.fr-highlight--caution}
        > La date de déclaration ne vous permet donc pas de distinguer l'imprimé rectificatif de l'imprimé initial car les deux imprimés ont toujours la même date de déclaration. Celle-ci correspond à la date du correctif. 
