---
- uid: 'dgfip/attestations_fiscales'
  position: 250
  path: '/v3/dgfip/unites_legales/{siren}/attestation_fiscale'
  perimeter:
    entity_type_description: |+
      Cette API délivre uniquement les attestations fiscales des **✅ entreprises soumises à l'impôt sur les sociétés (IS)**. 

      L'API ne permet pas de récupérer les attestations fiscales : 
      - ❌ des entreprises qui relèvent de l'impôt sur le revenu (IR), les entreprises individuelles sont donc notamment exclues ;
      - ❌ des sociétés ayant été créées durant l'année en cours ;
      - ❌ des sociétés bénéficiant d’un plan de règlement, redressement, sauvegarde ou conciliation ainsi que les sociétés ayant formulé un recours contentieux assorti d’un sursis de paiement.

      {:.fr-highlight}
      Pour ces dernières entreprises, l'obtention d'une attestation fiscale est possible en transmettant le [formulaire n° 3666](https://www.impots.gouv.fr/formulaire/3666-sd/attestation-de-regularite-fiscale){:target="_blank"} à leur service des impôts des entreprises. Ces entreprises ne peuvent pas bénéficier du service en ligne disponible sur le site [www.impots.gouv.fr](www.impots.gouv.fr){:target="_blank"}, conformément au [bulletin officiel des impôts du 7 décembre 2016 référencé BOI-DJC-ARF-20161207](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant%3DBOI-DJC-ARF-20161207){:target="_blank"}.

      {:.fr-highlight.fr-highlight--caution}
      > **⚠️ Cette API n'est pas fiable pour ❌ les sociétés "filles" appartenant à un groupe de société**.
      >
      > Une attestation peut être renvoyée en cas d'appel d'une entreprise "fille", mais cette attestation ne sera pas valable car incomplète. En effet, il manquera les informations de la société "mère".
      > Il est de votre ressort de vérifier si l'entreprise est membre ou non d'un groupe de sociétés imposé selon le régime fiscal d'intégration visé à l'[article 223 A du CGI](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042340402/){:target="_blank"} afin de ne pas utiliser une attestation qui ne serait pas valable. Deux API spécifiques à ces sociétés seront bientôt disponibles.

  call_id: "SIREN"
  opening: protected
  providers:
    - 'dgfip'
  keywords:
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'decret janvier 2019'
    - 'finances'
    - 'financier'
    - 'impôt'
    - 'TVA'
    - 'marchés publics'
    - 'aides publiques'
    - 'fraude'
  data:
    description: "Cette API délivre l'attestation de régularité fiscale d'une entreprise, au format PDF.
    L'attestation est **délivrée ✅ si l'entreprise est en règle de ses obligations** déclaratives et de paiement d'IS et de TVA."
  use_cases:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: L’api ne renvoie pas de pièce, cela signifie-t'il que l’entreprise n’est pas à jour ?
      a: |+
        Non, dans certains cas particuliers, l'API ne peut pas renvoyer l’attestation.
        Cela ne veut pas dire que l’entreprise n’est pas à jour. Il faut se rapprocher de l’entreprise pour lui demander la pièce directement.

        De plus, si une entreprise se voit refuser la délivrance de l’attestation pour cause de carence de ses déclarations
        ou de ses paiements, cette non-délivrance n’est pas définitive pour toute l’année N.
        Si ensuite elle régularise sa situation pour les années N-1 et antérieures, alors l’attestation de régularité lui sera délivrée.



    - q: Quelles obligations fiscales sont prises en compte ?
      a: |+
        L'attestation prend en compte :
        * ✅ la taxe sur la valeur ajoutée (TVA) ;
        * ✅ l'impôt sur les sociétés (IS).

        L'attestation ne concerne pas :
        * ❌ la contribution économique territoriale (CET) ;
        * ❌ la cotisation foncière des entreprises (CFE) ;
        * ❌ la cotisation sur la valeur ajoutée des entreprises (CVAE) ;
        * ❌ la taxe sur les salaires (TS).

        Plus d'informations disponibles dans le [BOFIP - Dispositions juridiques communes - Attestation de régularité fiscale.](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant%3DBOI-DJC-ARF-20161207){:target="_blank"}



    - q: L'attestation délivrée n'est pas signée, comment s'assurer de son authenticité ?
      a: |+
        L'attestation de régularité fiscale délivrée est une version dématérialisée. **Toutes les données délivrées par API Entreprise sont certifiées car prise à la source** ; dans ce cas précis, directement auprès de la DGFIP. Par ailleurs, le numéro de délivrance indiqué sur le PDF est unique et permet de s'assurer de l'authenticité du document.

        **Cette attestation à la même valeur juridique qu'une attestation signée par les services des impôts concernés**.

        Plus d'informations disponibles dans le [BOFIP - Dispositions juridiques communes - Attestation de régularité fiscale](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant%3DBOI-DJC-ARF-20161207){:target="_blank"}.


    - q: Quelle est la date de délivrance de l'attestation ?
      a: |+
        Théoriquement, l'attestation de régularité fiscale peut être obtenue tout au long de l'année et apprécie la situation de l'entreprise au dernier jour du mois précédant la demande de délivrance de l'attestation.

        En pratique, les dates de délivrance des attestations obtenues sur API Entreprise varient.



    - q: Pourquoi l'attestation délivrée par cette API n'est pas valable pour une entreprise filiale d'un groupe de sociétés ?
      a: |+
        Une société fille doit fournir deux attestations pour justifier de sa situation fiscale :
        * sa propre attestation, justifiant de ses propres obligations, à savoir le dépôt des déclarations de résultats et de TVA, ainsi que le paiement de la TVA ;
        * l'attestation de régularité fiscale de la société mère du groupe, qui confirme le paiement de l'impôt sur les société.

        Cette API ne permet pas d'entrer le numéro de SIREN de la société mère. Par conséquent, elle ne délivre que la partie concernant la société fille. Ce qui est insuffisant.

        Une API dédiée sera bientôt disponible.

        Plus d'informations disponibles dans le [BOFIP - Dispositions juridiques communes - Attestation de régularité fiscale](https://bofip.impots.gouv.fr/bofip/8485-PGP.html/identifiant%3DBOI-DJC-ARF-20161207){:target="_blank"}.
