---
- uid: 'urssaf/attestation_vigilance'
  position: 260
  path: '/v3/urssaf/unites_legales/{siren}/attestation_vigilance'
  perimeter:
    entity_type_description: |+
      ✅ Toutes les entreprises sont concernées, y compris les micro-entreprises.

      L'attestation est délivrée si l'entreprise :
      - s'est acquitée des cotisations et contributions dues à leur date normale d'exigibilité ;
      - a souscrit un plan d'apurement (planification des remboursements) des cotisations et contributions restant dues, qu'elle respecte ;
      - s'est acquitée des cotisations et contributions dues, mais n'est pas à jour dans le paiement des majorations et pénalités ;
      - ne s'est pas acquittée des cotisations et contributions dues mais en conteste le montant par recours contentieux.

      Le cadre précis de délivrance de l'attestation est expliqué sur le [site de l'URSSAF](https://www.urssaf.fr/portail/home/employeur/declarer-et-payer/obtenir-une-attestation/attestation-de-vigilance.html){:target="_blank"}.

      {:.fr-highlight}
      > Depuis 2021, la contribution annuelle de l'OETH (Obligation d'Emploi de Travailleur Handicapé), fait partie des contribution dues pour obtenir l'attestation.
      > Cette compétence était auparavant attribuée à l'AGEFIPH.

    entities:
      - entreprises
  opening: protected
  call_id: "SIREN"
  parameters:
    - Numéro de SIREN de l'entreprise
  use_cases:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
  providers:
    - 'acoss'
  data:
    description: Cette API délivre l'attestation de vigilance, au format PDF.
  faq:
    - q: Combien de temps est valide l'attestation de vigilance ?
      a: |+
        L'attestation de vigilance est valide 6 mois à compter de la dernière date de période analysée. Celle-ci dépend de la situation de chaque entreprise et de la dernière déclaration enregistrée dans le système.

    - q: L'API ne renvoie pas de pièce, peut-on considérer que l'entreprise n'est pas à jour ?
      a: |+
        Non, dans certain cas, l'API ne peut pas délivrer l'attestation, cela ne signifie pas que l'entreprise n'est pas à jour.
