---
- uid: 'msa/conformites_cotisations'
  path: '/v3/msa/etablissements/{siret}/conformite_cotisations'
  position: 270
  perimeter:
    entity_type_description: |+
      ✅ Les entreprises relevant du régime agricole, de la MSA et donc concernées par cette API sont les suivantes : 
      - les **exploitations de culture, d'élevage, de dressage** ;
      - les entreprises de **travaux agricoles** ;
      - les entreprises de **travaux forestiers** ;
      - les établissements de conchyliculture et de pisciculture ; 
      - les activités de pêche maritime à pied professionnelles, sauf pour celles qui relèvent du régime social des marins.
      
      ℹ️ La description précise des entreprises dont les cotisations sont recouvrées par la MSA est disponible dans les [articles L722-1 à L722-7 du Code rural et de la pêche maritime](https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006071367/LEGISCTA000006183040/2022-05-26/){:target="_blank"}.
      
      ❌ Les entreprises qui relèvent du régime général ou d'autres régimes sociaux ne sont pas concernées par cette API.
      
    updating_rules_description: |+
      Cette API interroge en direct l'Administration des systèmes d'information des organismes sociaux (MSA URSSAF). Les données transmises sont donc **à jour, en temps réél**, des dernières informations connues par la MSA.
    entities:
      - entreprises
  call_id: "SIRET"
  provider_uids:
    - 'msa'
  keywords:
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'fraude'
    - 'agricole'
    - 'agriculture'
    - 'maraichage'
    - 'producteur'
    - 'culture'
    - 'ferme'
    - 'marchés publics'
    - 'subventions'
    - 'aides'
  data:
    description: |+
      Cette API indique si l'entreprise est à jour de ses cotisations sociales auprès de la MSA. Il existe donc **trois situations possibles** pour une entreprise :
      - L'entreprise est **à jour de ses cotisations sociales** auprès de la MSA ;
      - L'entreprise **n’est pas à jour** de ses cotisations sociales ;
      - La régularité de l'entreprise est inconnue. Une **analyse est à effectuer** par un agent caisse de la MSA pour savoir si le débiteur est à jour ou pas. Il vous faudra relancer un appel ultérieurement, le temps que l'agent analyse la situation et la mette à jour dans le système d'information.
       


      {:.fr-highlight}
      Depuis 2021, la conformité n'est délivrée que si la contribution annuelle de l'OETH (Obligation d’Emploi de Travailleur Handicapé) a été acquittée par l'entreprise. Cette compétence était auparavant attribuée à l'AGEFIPH.

  opening: protected
  format:
    - Donnée structurée JSON
  availability: 
    opening_time:
      7jours/7 et 24h/24
  use_cases:
    - Marchés publics
  use_cases_optional:
    - Aides publiques
    - Détection de la fraude
  use_cases_forbidden:
    - Préremplissage d'un formulaire
    - Portail gestion relation usager
  parameters:
    - Numéro de SIRET de l'établissement
