---
- uid: 'probtp/conformites_cotisations_retraite'
  path: '/v3/probtp/etablissements/{siret}/conformite_cotisations_retraite'
  position: 280
  perimeter:
    entity_type_description: "✅ Entreprises du secteur du bâtiment et des travaux publics."
    entities:
      - entreprises
  call_id: "SIRET"
  providers:
    - 'probtp'
  data:
    description: "Cette API délivre l&apos;attestation PROBTP au format PDF permettant de savoir si l&apos;entreprise est à jour de ses cotisations retraite à la Protection Sociale du Bâtiment et des Travaux publics (PROBTP)."
  opening: protected
  use_cases:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
  parameters:
    - Numéro de SIRET de l'établissement
