---
- uid: 'cnetp/attestations_cotisations_conges_payes_chomage_intemperies'
  path: '/v3/cnetp/unites_legales/{siren}/attestation_cotisations_conges_payes_chomage_intemperies'
  position: 300
  perimeter:
    entity_type_description: |+
      Cette API couvre les **entreprises exerçant une ou plusieurs activités entrant dans le champ d'application des conventions collectives nationales étendues des Travaux Publics et du Bâtiment** :
      - ✅ Convention collective nationale des ouvriers des travaux publics du 15 décembre 1992 (étendue par arrêté du 27 mai 1993) ;
      - ✅ Convention collective nationale des ETAM des travaux publics du 12 juillet 2006 (étendue par arrêté du 28 juin 2007) ;
      - ✅ Convention collective nationale des cadres des travaux publics du 20 novembre 2015 (étendue par arrêté du 5 juin 2020).

      Toutes les attestations sont disponibles pour les **entreprises en situation régulière** ❌ sauf pour celles qui règlent les cotisations dues à la CNETP au travers de l’URSSAF dans le cadre du Titre Emploi Service Entreprise (TESE).
    know_more_description: |+
      - le [site de la CNETP](https://www.cnetp.org/category/affiliation/){:target="_blank"} est une source d'information ;
      - l'[article D.3141-12 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000020572124/){:target="_blank"} définit les entreprises qui sont tenues d’adhérer auprès d'une Caisse de Congés Payés du BTP ;
        Dans les entreprises exerçant une ou plusieurs activités entrant dans le champ d'application des conventions collectives nationales étendues du bâtiment et des travaux publics, le service des congés est assuré, sur la base de celles-ci, par des caisses constituées à cet effet.
    entities:
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'cnetp'
  keywords:
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'btp'
    - 'bâtiment'
    - 'travaux'
    - 'marchés publics'
    - 'aides publiques'
    - 'fraude'
  data:
    description: |+
      Cette API permet d'obtenir au format PDF une attestation délivrée à l'entreprise sous réserve que celle-ci&nbsp; soit à jour de ses déclarations et du paiement de cotisations congés payés et chômage-intempéries.
  opening: protected
  use_cases:
    - Marchés publics
  use_cases_optional:
    - Aides publiques
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: L'API ne renvoie pas de pièce, peut-on considérer que l'entreprise n'est pas à jour ?
      a: |+
        Non, dans certains cas nous ne pouvons pas récupérer l’attestation. Notamment, cette API ne permet de récupérer les attestations des entreprises réglant leurs cotisations à la CNETP au travers de l'URSSAF (dans le cadre du TESE).
