---
- uid: 'insee/etablissements'
  position: 105
  path: '/v3/insee/sirene/etablissements/{siret}'
  perimeter:
    entity_type_description: &insee_etablissements_entity_type_description |+
      Cette API concerne les établissements inscrits au répertoire Sirene, qu'ils soient **"diffusibles" ou "non-diffusibles"** :

      - ✅ les établissements des personnes morales de droit privé : **les entreprises et les entrepreneurs individuels**, dont toutes celles et ceux immatriculés au registre du commerce et des sociétés (RCS) et/ou au répertoire des métiers (RCM).
      - ✅ les établissements des **associations ayant un numéro de SIRET**, délivré lorsqu'elles :
        * emploient du personnel salarié ;
        * sont soumises à la TVA ;
        * ont demandé ou bénéficient de transferts financiers publics.
      - ✅ les établissements des personnes morales de droit public : les **institutions et services de l'État** et les collectivités territoriales ;
      - ✅ Les établissements des organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.


      {:.fr-highlight}
      ✅ Depuis janvier 2022, les loueurs de meublés non professionnels (LMNP) et les particuliers employeurs, à l'exception des cas mentionnés au [2° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'être inscrits au répertoire Sirene.
      Cette modification intervient suite au [Décret n° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.


      ❌ Les établissements de gestion de paye de la fonction publique, bien que présents dans la base Sirene, ne sont pas concernés par cette API. Ils ont été immatriculés pour les seuls besoins de certaines administrations (les impôts, les URSSAF, la DGCP …).
      Leur diffusion à d'autres administrations n'est donc pas prévue.

    geographical_scope_description: &insee_etablissements_geographical_scope_description |+
      La base Sirene concerne les établissements implantés en métropole, dans les DOM et dans les collectivités d'Outre-Mer de Saint-Pierre-et-Miquelon, Saint-Barthélémy et Saint-Martin.

      ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l'État ou des communes est répertorié ;
      ❌ les entreprises ne sont donc pas disponibles.
    updating_rules_description: &insee_etablissements_updating_rules_description |+
      La mise à jour des données est faite **quotidiennement entre 0h et 3h** à l'Insee.
    know_more_description: &insee_etablissements_know_more_description |+
      L'[article R123-220 du Code du commerce](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904){:target="_blank"} liste les entités tenues d'être inclues dans le répertoire Sirene par l'Insee.
    entities:
    - entreprises
    - associations
  opening: protected
  call_id: &insee_etablissements_call_id SIRET
  parameters: &insee_etablissements_parameters
    - Numéro de SIRET de l'établissement
  format: &insee_etablissements_format
    - Donnée structurée JSON 
  availability: 
    opening_time: &insee_etablissements_opening_time
      7jours/7 et 24h/24 
  use_cases:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
  use_cases_forbidden:
    - Préremplissage d'un formulaire
    - Portail gestion relation usager
  provider_uids: &insee_etablissements_provider_uids
    - 'insee'
  keywords: &insee_etablissements_keywords
    - 'activité'
    - 'naf'
    - 'ape'
    - 'identité'
    - 'identification'
    - 'état'
    - 'effectif'
    - 'raison sociale'
    - 'nom'
    - 'numéro tva'
    - 'forme juridique'
    - 'localisation'
    - 'emplacement'
    - 'adresse'
    - 'commune'
    - 'région'
    - 'pays'
    - 'cedex'
    - 'cessation'
    - 'cessation'
    - 'clôture'
    - 'remplissage'
    - 'fraude'
    - 'aides'
    - 'marchés'
  data:
    description: &insee_etablissement_data_description |+
      À partir du numéro de SIRET de l'établissement, cette API délivre les **informations générales de celui-ci** et les **informations générales de l'unité légale** à laquelle l'établissement est rattaché.
  faq:
    - q: &insee_etablissements_faq_q1 Qu'est-ce que l'état administratif d'un établissement ?
      a: &insee_etablissements_faq_a1 |+
        L'état administratif d'un établissement a deux modalités : actif ou fermé.

        Lors de son inscription au répertoire Sirene, un établissement est, sauf exception, à l'état "actif".
        Le passage à l'état "fermé" découle de la prise en compte d'une déclaration de fermeture.

        Un établissement fermé peut être rouvert.

    - q: &insee_etablissements_faq_q2 Qu'est-ce qu'un "non-diffusible" ?
      a: &insee_etablissements_faq_a2 |+
        Parmi les entités présentes dans le répertoire Sirene, certaines, très majoritairement des personnes physiques, ont explicitement demandé de ne pas figurer en diffusion commerciale, en vertu de l'[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/){:target="_blank"}.

        Cela signifie qu'elles donnent accord de la diffusion de leur données uniquement à des organismes habilités et à des administrations. **De fait, leurs données ne sont pas publiques**.

        ⚠️ Attention les informations des personnes physiques ne sont plus accessibles pour quiconque une fois qu'elles ont cessé leur activité.

        ℹ️ Les unités de la Défense nationale font également partie des "non-diffusibles" mais ne sont accessibles que sur autorisation du Ministère de la Défense, conformément à l'[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/){:target="_blank"}

    - q: &insee_etablissements_faq_q3 Comment utiliser les informations des établissements "non-diffusibles" ?
      a: &insee_etablissements_faq_a3 |+
        En utilisant cette API, vous vous engagez à **tenir compte du statut de diffusion le plus récent** de l'entité appelée.
        Dans le cas où l'entité est indiquée comme \"non-diffusible\", vous vous engagez à n'utiliser leurs informations que dans le cadre strict de vos missions de service public, à ne pas les rediffuser ni les divulguer auprès de tiers non autorisés.

        {:.fr-highlight.fr-highlight--caution}
        > ⚠️ **Vous ne pouvez pas donc pas faire usage des données d'une entité "non-diffusible" pour du pré-remplissage.**

        {:.fr-highlight}
        > Il vous est par contre possible d'indiquer à l'entité "non-diffusible" qu'elle peut modifier son statut, même provisoirement, auprès de l'Insee à l'adresse suivante : [https://statut-diffusion-sirene.insee.fr](https://statut-diffusion-sirene.insee.fr){:target="_blank"}).

- uid: 'insee/etablissements_diffusibles'
  position: 100
  path: '/v3/insee/sirene/etablissements/diffusibles/{siret}'
  perimeter:
    entity_type_description: |+
      Cette API concerne les établissements inscrits au répertoire Sirene et "diffusibles" commercialement  :
      - ✅ les établissements des personnes morales de droit privé : **les entreprises et les entrepreneurs individuels**, dont toutes celles et ceux immatriculés au registre du commerce et des sociétés (RCS) et/ou au répertoire des métiers (RCM) ;
      - ✅ les établissements des personnes morales de droit public : les **institutions et services de l'État** et les collectivités territoriales ;
      - ✅ les établissements des **associations ayant un numéro de SIRET** délivré lorsqu'elles :
        * emploient du personnel salarié ;
        * sont soumises à la TVA ;
        * ont demandé ou bénéficient de transferts financiers publics.
      - ✅ Les établissements des organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.


      {:.fr-highlight}
      ✅ Depuis janvier 2022, les loueurs de meublés non professionnels (LMNP) et les particuliers employeurs, à l'exception des cas mentionnés au [2° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'être inscrits au répertoire Sirene.
      Cette modification intervient suite au [Décret n° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.


      ❌ Les établissements de gestion de paye de la fonction publique, bien que présents dans la base Sirene, ne sont pas concernés par cette API. Ils ont été immatriculés pour les seuls besoins de certaines administrations (les impôts, les URSSAF, la DGCP …).
      Leur diffusion à d'autres administrations n'est donc pas prévue.

      ❌ **Les établissements "non-diffusibles" ne sont pas couverts par cette API**, leurs informations sont appelables avec [cette API](<%= endpoint_path(uid: 'insee/etablissements') %>).

    geographical_scope_description: *insee_etablissements_geographical_scope_description
    updating_rules_description: *insee_etablissements_updating_rules_description
    know_more_description: *insee_etablissements_know_more_description
    entities:
    - entreprises
    - associations
  opening: public
  use_cases_optional:
    - Détection de la fraude
    - Marchés publics
    - Aides publiques
  use_cases:
    - Préremplissage d'un formulaire
    - Portail gestion relation usager
  format: *insee_etablissements_format
  availability: 
    opening_time: *insee_etablissements_opening_time
  parameters: *insee_etablissements_parameters
  call_id: *insee_etablissements_call_id
  provider_uids: *insee_etablissements_provider_uids
  keywords: *insee_etablissements_keywords
  data:
    description: *insee_etablissement_data_description
  faq:
    - q: *insee_etablissements_faq_q1
      a: *insee_etablissements_faq_a1
    - q: *insee_etablissements_faq_q2
      a: *insee_etablissements_faq_a2
    - q: *insee_etablissements_faq_q3
      a: *insee_etablissements_faq_a3
