---
- uid: 'qualibat/certifications_batiment'
  path: '/v3/qualibat/etablissements/{siret}/certification_batiment'
  position: 330
  perimeter:
    entity_type_description: |+
      ✅ Toutes les **entreprises et les artisans du bâtiment** ayant obtenu le label de fiabilité [Qualibat](https://www.qualibat.com/){:target="_blank"}.
    entities:
      - associations
      - entreprises
  call_id: "SIRET"
  provider_uids:
    - 'qualibat'
  keywords:
    - 'btp'
    - 'bâtiment'
    - 'travaux'
    - 'rénovation'
    - 'énergie'
    - 'capacité'
    - 'expertise'
    - 'technicité'
    - 'qualité'
    - 'marchés publics'
  data:
    description: |+
      Cette API délivre le certificat Qualibat de l'entreprise au format PDF, comportant de nombreuses informations.

      **Des informations sur l'établissement :**
      - raison sociale, date de création, forme juridique, code NACE et capital social ;
      - adresse et coordonnées de l'entreprise ;
      - nom et fonction des dirigeants responsables ;
      - registre de commerce ou de répertoire des métiers auquel l'entreprise est rattachée ;
      - numéro d'affiliation à la caisse de congés payés ;
      - régularité de la situation fiscale et sociale ;
      - assurances responsabilité civile et travaux ;
      - effectif moyen et chiffre d'affaires hors taxes.

      **Des informations sur la qualification :**
      - code à quatre chiffres de la capacité technique reconnue à l'entreprise dans une des 9 activités détaillées dans la [nomenclature Qualibat](https://www.qualibat.com/nomenclature/){:target="_blank"} ;
      - titre de cette capacité ;
      - niveau de technicité ;
      - classification partielle : les moyens humains dont dispose l'entreprise dans l'activité pour laquelle elle est qualifiée sont précisés.
      - date d'attribution : date à laquelle la qualification a été attribuée ou dernièrement renouvellée ;
      - date d'échéance : date d'expiration de validité de la qualification ;
      - système qualité : dans la mesure où l'entreprise a mis en place une démarche qualité certifiée par Qualibat, la certification de son système qualité est mentionnée en annexe.

      **Des informations liées au certificat :**
      - millésime du certificat ;
      - durée de validité ;
      - numéro d'identification du certificat.

      [**Source : Qualibat**](https://www.qualibat.com/){:target="_blank"}
  opening: public
  format:
    - URL vers le certificat en PDF
  availability: 
    opening_time:
      7jours/7 et 24h/24
  use_cases_optional:
    - Marchés publics
    - Aides publiques
    - Préremplissage d'un formulaire
    - Détection de la fraude
  parameters:
    - Numéro de SIRET de l'établissement
