---
- uid: 'inpi/modeles'
  path: '/v3/inpi/unites_legales/{siren}/modeles'
  position: 370
  perimeter:
    entity_type_description: |+
      Cette API délivre ✅ uniquement les dessins & modèles pour lesquels un SIREN était précisé lors du dépôt par l'entreprise. L'INPI indique qu'environ **50% des dépôts** effectués au niveau français sont rattachés à un SIREN.
    geographical_scope_description: |+
      ✅ Seuls les dessins & modèles (avec SIREN) déposés **au niveau français depuis 1910** sont disponibles. 
      ❌ Les modèles déposés au niveau européen ne sont pas transmis par l'INPI.
      ❌ Les modèles déposés au niveau international ne sont pas renvoyés par cette API car le taux de sirenage est de 0%.
    updating_rules_description: |+
      La mise a jour des données est faite **une semaine sur deux, le vendredi**.
    entities:
      - associations
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'inpi'
  data:
    description: |+
      Cette API délivre :
      - le **nombre de modèles déposés** par l'entreprise, pour lesquels le SIREN était précisé lors du dépôt.
      - Une **liste des 5 derniers modèles déposés** est également renvoyée, et permet d'obtenir, entre autres, les informations suivantes&nbsp;:
        * le titre du modèle et le numéro national sous lequel le modèle est enregistré ;
        * la date de dépôt et la date de publication ;
        * le nom de l'entité ayant déposé le modèle ;
        * le nombre de vues du modèle.
      
      Il vous est possible d'augmenter ou de réduire le nombre de dessins & modèles pour lesquels les informations sont renvoyées, en paramétrant la requête avec un nombre entre 1 et 20.
  opening: public
  format:
    - Donnée structurée JSON
  availability: 
    opening_time:
      7jours/7 et 24h/24
  use_cases_optional:
    - Marchés publics
    - Aides & subventions publiques
    - Détection de la fraude
    - Portail GRU - Pré-remplissage
    - Portail GRU - Instruction des démarches
  parameters:
    - Numéro de SIREN de l'unité légale
