---
- uid: 'infogreffe/mandataires_sociaux'
  path: '/v3/infogreffe/rcs/unites_legales/{siren}/mandataires_sociaux'
  position: 110
  perimeter:
    entity_type_description: |+
      Cette API concerne ✅ **toutes les entreprises inscrites au registre du commerce et des sociétés** (RCS).
      
      Il s'agit des entreprises ayant une activité commerciale. Pour plus de détails, consulter [le site du ministère de l'économie](https://www.economie.gouv.fr/entreprises/registre-commerce-societes-rcs){:target="_blank"}
    updating_rules_description: |+
      Les données sont **mises à jour en temps réel** avec les greffes. La donnée est donc la plus récente possible, _modulo_ le temps de saisie nécessaire pour les greffiers.
    entities:
      - entreprises
  call_id: "SIREN"
  provider_uids:
    - 'infogreffe'
  keywords:
    - 'fonction'
    - 'nom'
    - 'prénom'
    - 'mandataire'
    - 'dirigeant'
    - 'date de naissance'
    - 'lieu de naissance'
    - 'actionnaire'
    - 'bénéficiare'
    - 'fraude'
  data:
    description: |+
      Cette API délivre **tous les mandataires sociaux  et leur fonction** au sein de l'entreprise&nbsp;:
      - S'il s'agit de personnes morales : le numéro de SIREN, la raison sociale et le nom du greffe seront précisés ;
      - S'il s'agit de personnes physiques : le nom, le prénom, la date de naissance, le lieu de naissance de la personne physique(commune et pays) ainsi que la nationalité seront indiqués.
  opening: protected
  format:
    - Donnée structurée JSON 
  availability: 
    opening_time:
      7jours/7 et 24h/24 
  use_cases:
    - Aides & subventions publiques
    - Détection de la fraude
  use_cases_optional:
    - Marchés publics
    - Portail GRU - Instruction des démarches
  use_cases_forbidden:
    - Portail GRU - Préremplissage
  parameters:
    - Numéro de SIREN de l'unité légale
  faq:
    - q: "Quelle différence avec les données de l'API Extrait RCS d'Infogreffe ?"
      a: |+
        L'[API Extrait RCS - Infogreffe](<%= endpoint_path(uid: 'insee/infogreffe/rcs/extrait') %>) permet aussi d'accéder à la liste des mandataires sociaux d'une unité légale. Issues du même fournisseur Infogreffe, la différence se trouve au niveau de l'ouverture et de la précision des données.

        Cette API mandataires sociaux permet d'accéder à des données protégées : 
        - ✅ le lieu de naissance (commune et pays) des personnes physiques listées ;
        - ✅ leur nationalité.
        <br/>

        {:.fr-highlight}
        **Pour accéder à cette API, il vous faudra donc justifier du besoin d'obtenir ces informations protégées**. <br />
        **Cette API n'est pas adaptée pour du préremplissage**. Pour apporter une aide à la saisie à vos utilisateurs, comme par exemple pour le [cas d'usage Préremplissage - Portail GRU](<%= cas_usage_path('portail_gru') %>), vous devez utiliser la donnée publique issue de l'[API Extrait RCS - Infogreffe](<%= endpoint_path(uid: 'insee/infogreffe/rcs/extrait') %>).






