---
- uid: 'insee/unites_legales'
  path: '/v3/insee/sirene/unites_legales/{siren}'
  position: 125
  perimeter:
    description: |+
    entity_type_description: |+
      Cette API concerne les unités légales inscrites au répertoire Sirene, qu'elles soient **"diffusibles" ou "non-diffusibles"** :
      - ✅ les personnes morales de droit privé : les **entreprises** dont toutes celles immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RCM) figurent dans la base Sirene ;
      - ✅ les **associations ayant un numéro de SIREN**, délivré lorsqu'elles :
        * emploient du personnel salarié ;
        * sont soumises à la TVA ;
        * ont demandé ou bénéficient de transferts financiers publics.
      - ✅ les personnes morales de droit public : les **institutions et services de l'État** et les collectivités territoriales ;
      - ✅ Les organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.

      {:.fr-highlight}
      ✅ Depuis janvier 2022, les loueurs de meublés non professionnels (LMNP) et les particuliers employeurs, à l'exception des cas mentionnés au [2° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'être inscrits au répertoire Sirene.
      Cette modification intervient suite au [Décret n° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.

    geographical_scope_description: &insee_unites_legales_geographical_scope_description |+
      La base Sirene concerne les unités implantées en métropole, dans les DOM et dans les collectivités d'Outre-Mer de Saint-Pierre-et-Miquelon, Saint-Barthélémy et Saint-Martin.

      ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l'État ou des communes est répertorié ;
      ❌ les entreprises ne sont donc pas disponibles.

    updating_rules_description: &insee_unites_legales_updating_rules_description |+
      La mise a jour des données est **faite quotidiennement entre 0h et 3h** à l'INSEE.

    know_more_description: &insee_unites_legales_know_more_description |+
      L'[article R123-220 du Code du commerce](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904){:target="_blank"} liste les entités tenues d'être inclues dans le répertoire Sirene par l'Insee.
    entities:
      - entreprises
      - associations
  opening: protected
  call_id: &insee_unites_legales_call_id SIREN
  parameters: &insee_unites_legales_parameters
    - Numéro de SIREN de l'unité légale
  format: &insee_unites_legales_format
    - Donnée structurée JSON 
  availability: 
    opening_time: &insee_unites_legales_opening_time
      7jours/7 et 24h/24 
  use_cases_optional:
    - Marchés publics
    - Aides & subventions publiques
    - Détection de la fraude
  use_cases_forbidden:
    - Portail GRU - Préremplissage
    - Portail GRU - Instruction des démarches
  provider_uids: &insee_unites_legales_provider_uids
    - 'insee'
  keywords: &insee_unites_legales_keywords
    - 'activité'
    - 'naf'
    - 'ape'
    - 'identité'
    - 'identification'
    - 'état'
    - 'effectif'
    - 'raison sociale'
    - 'nom'
    - 'numéro tva'
    - 'forme juridique'
    - 'cessation'
    - 'clôture'
    - 'création'
    - 'remplissage'
    - 'fraude'
    - 'aides'
    - 'marchés'
  data:
    description: &insee_unites_legales_data_description |+
      Cette API délivre **uniquement les informations de référence des unités légales**.

      Pour obtenir :
      - les informations des établissements, utilisez [cette API pour les "diffusibles"](<%= endpoint_path(uid: 'insee/etablissements') %>) et [cette API pour tous les établissements, y compris les "non-diffusibles"](<%= endpoint_path(uid: 'insee/etablissements_diffusibles') %>) ;
      - l'adresse des établissements, [cette API pour les "diffusibles"](<%= endpoint_path(uid: 'insee/adresse_etablissements_diffusibles') %>) et [cette API pour tous les établissements, y compris les "non-diffusibles"](<%= endpoint_path(uid: 'insee/adresse_etablissements') %>) ;
      - les mandataires sociaux, [cette API](<%= endpoint_path(uid: 'infogreffe/mandataires_sociaux') %>) .
      - les informations du siège social, [cette API pour les "diffusibles"](<%= endpoint_path(uid: 'insee/siege_social_diffusibles') %>) et [cette API pour tous les sièges sociaux, y compris les "non-diffusibles"](<%= endpoint_path(uid: 'insee/siege_social') %>).
  faq:
    - q: &insee_unites_legales_faq_q1 Qu'est-ce que l'état administratif d'une entité légale ?
      a: &insee_unites_legales_faq_a1 |+
        L'état administratif indique si une unité légale est active ou cessée.

        **Pour les personnes morales**, l'unité légale est considérée comme juridiquement cessée si :
        - il y a eu dépôt de la déclaration de disparition de la personne morale ;
        - elle a été inscrite sans activité à sa demande. Dans le cas d'une création au répertoire Sirene mais sans avoir encore démarré une activité (activité principale provisoire “0000Z”) ;
        - elle n'a plus d'établissement en activité.

        **Pour les personnes physiques**, l'unité légale est considérée comme juridiquement cessée si :
        - l'exploitant de l'unité légale décède ;
        - l'exploitant dépose une cessation d'activité.

          En dehors de ces cas, l'état administratif de l'unité légale est toujours "actif".

    - q: &insee_unites_legales_faq_q2 Une unité légale semble être successivement active puis cessée puis active, est-ce normal ?
      a: &insee_unites_legales_faq_a2 |+
        **Pour les personnes physiques**, dans le cas où l'exploitant déclare la cessation de son activité, puis la reprend quelque temps plus tard, **l'état administratif est réversible**. Il est donc normal d'avoir des périodes successives d'état actif puis cessé pour les personnes physiques.

        En revanche, **pour les personnes morales, l'état administratif est en théorie irréversible**.


    - q: &insee_unites_legales_faq_q3 Une unité légale est active mais tous ses établissements sont fermés, est-ce une erreur ?
      a: &insee_unites_legales_faq_a3 |+
        Même si tous les établissements d'une unité légale sont fermés, y compris son établissement siège, **une unité légale reste active tant que la cessation juridique n'a pas été prononcée.

        Une réactivation est même encore possible. Le SIREN continue donc d'avoir un statut "actif" au répertoire.


    - q: Qu'est-ce qu'un "non-diffusible" ?
      a: |+
        Parmi les entités présentes dans le répertoire Sirene, certaines, très majoritairement des personnes physiques, ont explicitement demandé de ne pas figurer en diffusion commerciale,
        en vertu de l'[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/){:target="_blank"}.

        Cela signifie qu'elles donnent accord de la diffusion de leur données uniquement à des organismes habilités et à des administrations. **De fait, leurs données ne sont pas publiques**.

        ⚠️ Attention les informations des personnes physiques ne sont plus accessibles pour quiconque une fois qu'elles ont cessé leur activité.

        ℹ️ Les unités de la Défense nationale font également partie des \"non-diffusibles\" mais ne sont accessibles que sur autorisation du Ministère de la Défense, conformément à l'[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/){:target="_blank"}


    - q: Comment utiliser les informations des unités légales "non-diffusibles" ?
      a: |+
        En utilisant cette API, vous vous engagez à **tenir compte du statut de diffusion le plus récent** de l'entité appelée.
        Dans le cas où l'entité est indiquée comme "non-diffusible", vous vous engagez à n'utiliser leurs informations que dans le cadre strict de vos missions de service public, à ne pas les rediffuser ni les divulguer auprès de tiers non autorisés.

        {:.fr-highlight.fr-highlight--caution}
        > ⚠️ **Vous ne pouvez pas donc pas faire usage des données d'une entité "non-diffusible" pour du pré-remplissage.**

        {:.fr-highlight}
        > Il vous est par contre possible d'indiquer à l'unité légale "non-diffusible" qu'elle peut modifier son statut, même provisoirement, auprès de l'Insee à l'adresse suivante : [https://statut-diffusion-sirene.insee.fr](https://statut-diffusion-sirene.insee.fr}{:target="_blank"}).

- uid: 'insee/unites_legales_diffusibles'
  path: '/v3/insee/sirene/unites_legales/diffusibles/{siren}'
  position: 120
  perimeter:
    entity_type_description: |+
      Cette API concerne les unités légales inscrites au répertoire Sirene et **"diffusibles" commercialement** :
      - ✅ les personnes morales de droit privé : les **entreprises**, dont toutes celles immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RCM) figurent dans la base Sirene ;
      - ✅ les **associations ayant un numéro de SIREN**, délivré lorsqu'elles :
        * emploient du personnel salarié ;
        * sont soumises à la TVA ;
        * ont demandé ou bénéficient de transferts financiers publics.
      - ✅ les personnes morales de droit public : les **institutions et services de l'État** et les collectivités territoriales ;
      - ✅ Les organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.

      {:.fr-highlight}
      ✅ Depuis janvier 2022, les loueurs de meublés non professionnels (LMNP) et les particuliers employeurs, à l'exception des cas mentionnés au [2° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'être inscrits au répertoire Sirene.
      Cette modification intervient suite au [Décret n° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.

      ❌ **Les unités légales "non-diffusibles" ne sont pas concernées par cette API**, leurs informations sont appelables avec [cette API](<%= endpoint_path(uid: 'insee/unites_legales') %>).

    geographical_scope_description: *insee_unites_legales_geographical_scope_description
    updating_rules_description: *insee_unites_legales_updating_rules_description
    know_more_description: *insee_unites_legales_know_more_description
    entities:
    - entreprises
    - associations
  opening: public
  format: *insee_unites_legales_format
  availability: 
    opening_time: *insee_unites_legales_opening_time
  use_cases_optional:
    - Détection de la fraude
    - Marchés publics
    - Aides & subventions publiques
    - Portail GRU - Préremplissage
    - Portail GRU - Instruction des démarches
  parameters: *insee_unites_legales_parameters
  call_id: *insee_unites_legales_call_id
  provider_uids: *insee_unites_legales_provider_uids
  keywords: *insee_unites_legales_keywords
  data:
    description: *insee_unites_legales_data_description
  faq:
    - q: *insee_unites_legales_faq_q1
      a: *insee_unites_legales_faq_a1
    - q: *insee_unites_legales_faq_q2
      a: *insee_unites_legales_faq_a2
    - q: *insee_unites_legales_faq_q3
      a: *insee_unites_legales_faq_a3
