---
- uid: 'insee/siege_social'
  path: '/v3/insee/sirene/unites_legales/{siren}/siege_social'
  position: 135
  perimeter:
    entity_type_description: |+
      Cette API concerne les siÃ¨ges sociaux des unitÃ©s lÃ©gales inscrites au rÃ©pertoire Sirene, qu'elles soient **"diffusibles" ou ["non-diffusibles"](#faq_entry_2_endpoint_insee_siege_social)** :

      - âœ… les siÃ¨ges sociaux des personnes morales de droit priveÌ : **les entreprises et les entrepreneurs individuels**, dont toutes celles et ceux immatriculeÌs au registre du commerce et des socieÌteÌs (RCS) et/ou au reÌpertoire des meÌtiers (RCM) ;
      - âœ… les siÃ¨ges sociaux **associations ayant un numÃ©ro de SIRET** dÃ©livrÃ© lorsqu'elles :
        * emploient du personnel salariÃ© ;
        * sont soumises Ã  la TVA ;
        * ont demandÃ© ou bÃ©nÃ©ficient de transferts financiers publics.
      - âœ… les siÃ¨ges sociaux des personnes morales de droit public : les **institutions et services de l'EÌtat** et les collectiviteÌs territoriales ;
      - âœ… Les siÃ¨ges sociaux des organismes publics ou privÃ©s et les entreprises Ã©trangÃ¨res qui ont une reprÃ©sentation ou une activitÃ© en France.


      {:.fr-highlight}
      âœ… Depuis janvier 2022, les loueurs de meublÃ©s non professionnels (LMNP) et les particuliers employeurs, Ã  l'exception des cas mentionnÃ©s au [2Â° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'Ãªtre inscrits au rÃ©pertoire Sirene.
      Cette modification intervient suite au [DÃ©cret nÂ° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.


      âŒ Les Ã©tablissements de gestion de paye de la fonction publique, bien que prÃ©sents dans la base Sirene, ne sont pas concernÃ©s par cette API. Ils ont Ã©tÃ© immatriculÃ©s pour les seuls besoins de certaines administrations (les impÃ´ts, les URSSAF, la DGCP â€¦).
      Leur diffusion Ã  d'autres administrations n'est donc pas prÃ©vue.

    geographical_scope_description: &insee_siege_social_geographical_scope_description |+
      La base Sirene concerne les unitÃ©s lÃ©gales implanteÌes en meÌtropole, dans les DROM et dans les collectiviteÌs d'Outre-Mer de Saint-Pierre-et-Miquelon, Saint-BartheÌleÌmy et Saint-Martin.
      âš ï¸ Pour la Nouvelle-CalÃ©donie, la PolynÃ©sie franÃ§aise, et Wallis-et-Futuna, seul le secteur public administratif, de l'Ã‰tat ou des communes est rÃ©pertoriÃ© ;
      âŒ les siÃ¨gs sociaux des entreprises ne sont donc pas disponibles.

    updating_rules_description: &insee_siege_social_updating_rules_description |+
      La mise a jour des donnÃ©es est faite **quotidiennement entre 0h et 3h** Ã  l'Insee.
    know_more_description: &insee_siege_social_know_more_description |+
      L'[article R123-220 du Code du commerce](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904){:target="_blank"} liste les entitÃ©s tenues d'Ãªtre inclues dans le rÃ©pertoire Sirene par l'Insee.

      {:.fr-icon-arrow-right-line .fr-link--icon-right}
      [ğŸ¦¸ **Le futur des â€œnon-diffusiblesâ€** - Publication 14/12/2022](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles)
    entities: &insee_siege_entities
    - entreprises
    - associations
  opening: protected
  call_id: &insee_siege_social_call_id SIREN
  parameters: &insee_siege_social_parameters
    - NumÃ©ro de SIREN de l'unitÃ© lÃ©gale
  format: &insee_siege_social_format
    - DonnÃ©e structurÃ©e JSON 
  availability: 
    opening_time: &insee_siege_social_opening_time
      7jours/7 et 24h/24 
  use_cases:
    - DÃ©tection de la fraude
    - MarchÃ©s publics
  use_cases_optional:
    - Aides & subventions publiques
    - Portail GRU - Instruction des dÃ©marches
  use_cases_forbidden:
    - Portail GRU - PrÃ©remplissage
  provider_uids: &insee_siege_social_provider_uids
    - 'insee'
  keywords: &insee_siege_social_keywords
    - 'activitÃ©'
    - 'naf'
    - 'ape'
    - 'identitÃ©'
    - 'identification'
    - 'Ã©tat'
    - 'effectif'
    - 'raison sociale'
    - 'nom'
    - 'numÃ©ro tva'
    - 'forme juridique'
    - 'localisation'
    - 'emplacement'
    - 'adresse'
    - 'commune'
    - 'rÃ©gion'
    - 'pays'
    - 'cedex'
    - 'cessation'
    - 'clÃ´ture'
    - 'crÃ©ation'
    - 'siÃ¨ge'
    - 'remplissage'
    - 'fraude'
    - 'aides'
    - 'marchÃ©s'
  data:
    description: &insee_siege_social_provider_uids_data_description |+
      Cette API dÃ©livre les **informations gÃ©nÃ©rales d'un siÃ¨ge social Ã  partir du numÃ©ro de SIREN de son unitÃ© lÃ©gale**.
  faq:
    - q: &insee_siege_social_provider_uids_faq_q1 Qu'est-ce que l'Ã©tat administratif du siÃ¨ge social ?
      a: &insee_siege_social_provider_uids_faq_a1 |+
        Lâ€™Ã©tat administratif dâ€™un Ã©tablissement a deux modalitÃ©s : "actif" ou "fermÃ©".

        Lors de son inscription au reÌpertoire Sirene, un eÌtablissement est, sauf exception, aÌ€ l'eÌtat "actif".

        Le passage aÌ€ lâ€™eÌtat "fermÃ©" deÌcoule de la prise en compte d'une deÌclaration de fermeture.

        Un eÌtablissement fermeÌ peut eÌ‚tre rouvert.

    - q: &insee_siege_social_provider_uids_faq_q2 "L'Ã©tat administratif du siÃ¨ge social est fermÃ© mais l'unitÃ© lÃ©gale est active, est-ce une erreur ?"
      a: &insee_siege_social_provider_uids_faq_a2 |+
        MÃªme si tous les Ã©tablissements d'une entreprise sont fermÃ©s, y compris son Ã©tablissement siÃ¨ge, **une unitÃ© lÃ©gale reste active tant que la cessation juridique n'a pas Ã©tÃ© prononcÃ©e**.

        Une rÃ©activation est mÃªme encore possible. Le SIREN de l'unitÃ© lÃ©gale continue donc d'avoir un statut "actif" au rÃ©pertoire."

    - q: &insee_siege_social_provider_uids_faq_q3 Qu'est-ce qu'un "non-diffusible" ?
      a: &insee_siege_social_provider_uids_faq_a3 |+
        **La non-diffusion commerciale :**
        Parmi les entitÃ©s prÃ©sentes dans le rÃ©pertoire Sirene, certaines, trÃ¨s majoritairement des personnes physiques, ont explicitement demandÃ© de ne pas figurer en diffusion commerciale, en vertu de l'[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/){:target="_blank"}.

        Cela signifie qu'elles donnent accord de la diffusion de leur donnÃ©es uniquement Ã  des organismes habilitÃ©s et Ã  des administrations. **De fait, leurs donnÃ©es ne sont pas publiques**.

        Ã€ partir de mars 2024, le fonctionnement des non-diffusibles commerciaux Ã©volue, certaines donnÃ©es seront disponibles pour du prÃ©-remplissage et les personnes morales pourront dÃ©cider de passer en diffusion partielle. Lire notre publication du 14/12/2022 : [ğŸ¦¸&nbsp;**Le futur des â€œnon-diffusiblesâ€**](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles).
       
        <br>
        **La non-diffusion pour d'autres raisons :**
        Certaines entitÃ©s ne sont pas diffusibles pour d'autres raisons que la non-diffusion commerciale. C'est par exemple le cas : 
        - des Ã©tablissements de gestion de paye de la fonction publique immatriculÃ©s pour les seuls besoins de certaines administrations (les impÃ´ts, les URSSAF, la DGCP â€¦) et donc uniquement accessibles Ã  ces administrations fiscales.
        - des unitÃ©s de la DÃ©fense nationale, accessibles sur autorisation du MinistÃ¨re de la DÃ©fense, conformÃ©ment Ã  lâ€™[article A 123-95 du Code du commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000020165032/2010-07-02){:target="_blank"}. **Ces unitÃ©s ne sont pas diffusÃ©es par l'API Entreprise**.


    - q: &insee_siege_social_provider_uids_faq_q4 Comment utiliser les informations des Ã©tablissements "non-diffusibles" ?
      a: &insee_siege_social_provider_uids_faq_a4 |+
        En utilisant cette API, vous vous engagez Ã  **tenir compte du statut de diffusion le plus rÃ©cent** de l'entitÃ© appelÃ©e.
        Dans le cas oÃ¹ l'entitÃ© est indiquÃ©e comme "non-diffusible", vous vous engagez Ã  n'utiliser leurs informations que dans le cadre strict de vos missions de service public, Ã  ne pas les rediffuser ni les divulguer auprÃ¨s de tiers non autorisÃ©s.

        {:.fr-highlight.fr-highlight--caution}
        > âš ï¸ **Vous ne pouvez pas donc pas faire usage des donnÃ©es d'une entitÃ© "non-diffusible" pour du prÃ©remplissage.**

        {:.fr-highlight}
        > Il vous est par contre possible d'indiquer Ã  l'entitÃ© "non-diffusible" qu'elle peut modifier son statut, mÃªme provisoirement, auprÃ¨s de l'Insee Ã  l'adresse suivante : [https://statut-diffusion-sirene.insee.fr](https://statut-diffusion-sirene.insee.fr){:target=\_blank"}.

        Ã€ partir de mars 2024, le fonctionnement des non-diffusibles commerciaux Ã©volue, certaines donnÃ©es seront disponibles pour du prÃ©-remplissage et les personnes morales pourront dÃ©cider de passer en diffusion partielle. Lire notre publication du 14/12/2022 : [ğŸ¦¸&nbsp;**Le futur des â€œnon-diffusiblesâ€**](https://entreprise.api.gouv.fr/blog/insee-non-diffusibles).

- uid: 'insee/siege_social_diffusibles'
  path: '/v3/insee/sirene/unites_legales/diffusibles/{siren}/siege_social'
  position: 130
  perimeter:
    entity_type_description: |+
      Cette API concerne les siÃ¨ges sociaux des unitÃ©s lÃ©gales inscrites au rÃ©pertoire Sirene et **"diffusibles" commercialement** :
      - âœ… les siÃ¨ges sociaux des personnes morales de droit priveÌ : **les entreprises et les entrepreneurs individuels**, dont toutes celles et ceux immatriculeÌs au registre du commerce et des socieÌteÌs (RCS) et/ou au reÌpertoire des meÌtiers (RCM ;
      - âœ… les siÃ¨ges sociaux **associations ayant un numÃ©ro de SIRET** dÃ©livrÃ© lorsqu'elles :
        * emploient du personnel salariÃ© ;
        * sont soumises Ã  la TVA ;
        * ont demandÃ© ou bÃ©nÃ©ficient de transferts financiers publics.
      - âœ… les siÃ¨ges sociaux des personnes morales de droit public : les **institutions et services de l'EÌtat** et les collectiviteÌs territoriales ;
      - âœ… Les siÃ¨ges sociaux des organismes publics ou privÃ©s et les entreprises Ã©trangÃ¨res qui ont une reprÃ©sentation ou une activitÃ© en France.


      {:.fr-highlight}
      âœ… Depuis janvier 2022, les loueurs de meublÃ©s non professionnels (LMNP) et les particuliers employeurs, Ã  l'exception des cas mentionnÃ©s au [2Â° de l'Article R123-220 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030783425/2022-05-31/){:target="_blank"}, ont l'obligation d'Ãªtre inscrits au rÃ©pertoire Sirene.
      Cette modification intervient suite au [DÃ©cret nÂ° 2021-1500 du 17 novembre 2021](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000044340276){:target="_blank"}.

      âŒ **Les siÃ¨ges sociaux ["non-diffusibles"](#faq_entry_2_endpoint_insee_siege_social_diffusibles) ne sont pas couverts par cette API**, leur adresse est appelable avec [cette API](<%= endpoint_path(uid: 'insee/siege_social') %>).

    geographical_scope_description: *insee_siege_social_geographical_scope_description
    updating_rules_description: *insee_siege_social_updating_rules_description
    know_more_description: *insee_siege_social_know_more_description
    entities: *insee_siege_entities
  opening: public
  format: *insee_siege_social_format
  availability: 
    opening_time: *insee_siege_social_opening_time
  use_cases:
    - MarchÃ©s publics
  use_cases_optional:
    - Aides & subventions publiques
    - DÃ©tection de la fraude
    - Portail GRU - PrÃ©remplissage
    - Portail GRU - Instruction des dÃ©marches
  parameters: *insee_siege_social_parameters
  call_id: *insee_siege_social_call_id
  provider_uids: *insee_siege_social_provider_uids
  keywords: *insee_siege_social_keywords
  data:
    description: *insee_siege_social_provider_uids_data_description
  faq:
    - q: *insee_siege_social_provider_uids_faq_q1
      a: *insee_siege_social_provider_uids_faq_a1
    - q: *insee_siege_social_provider_uids_faq_q2
      a: *insee_siege_social_provider_uids_faq_a2
    - q: *insee_siege_social_provider_uids_faq_q3
      a: *insee_siege_social_provider_uids_faq_a3
    - q: *insee_siege_social_provider_uids_faq_q4
      a: *insee_siege_social_provider_uids_faq_a4
