---
- uid: 'ministere_interieur/documents_associations'
  path: '/v3/ministere_interieur/rna/associations/{siret_or_rna}/documents'
  position: 155
  perimeter:
    entity_type_description: |+
      Cette API concerne ✅ **toutes les associations inscrites au répertoire national des associations (RNA)
      et/ou ayant déposé des documents sur le portail [lecompteasso.associations.gouv.fr](https://lecompteasso.associations.gouv.fr/){:target="_blank"}.

    updating_rules_description: |+
      Les documents provenant du RNA sont **mis à jour tous les jours**.
    entities:
      - associations
  call_id: "SIRET / RNA"
  provider_uids:
    - 'mi'
  data:
    description: |+
      Cette API indique le nombre de documents à télécharger, l’URL d’accès, le type et la date des documents.

      Les documents transmis peuvent être&nbsp;:
      - des récipissés de déclaration de création, de modification, et/ou de dissolution ;
      - les statuts de l'association ;
      - la liste des personnes habilitées à représenter l'association.

      ⚠️ Le type et le nombre de documents délivrés varient selon l'association.

  opening: public
  format:
    - URL vers documents PDF
  availability: 
    opening_time:
      7jours/7 et 24h/24 
  use_cases:
    - Marchés publics
    - Aides & subventions publiques
    - Détection de la fraude
    - Portail GRU - Instruction des démarches
  use_cases_optional:
    - Portail GRU - Pré-remplissage
    - Portail GRU - Instruction des démarches
  parameters:
    - Numéro de SIRET ou numéro RNA de l’association
