---
- uid: 'ministere_interieur/rna'
  path: '/v3/ministere_interieur/rna/associations/{siret_or_rna}'
  position: 150
  perimeter:
    entity_type_description: |+
      Cette API concerne ✅ **toutes les associations inscrites au répertoire national des associations (RNA) et/ou à l'Insee**.
      
    updating_rules_description: |+
      Les données sont **mises à jour tous les jours** depuis le RNA et depuis l'Insee. 
    entities:
      - associations
  call_id: "SIRET / RNA"
  providers:
    - 'mi'
  data:
    description: |+
      Cette API délivre les **informations déclarées par l'association en Préfecture**, entre autres :
      - le titre de l'association, et une description courte de ses activités ;
      - les dates de dépôt du dossier, de création de l'association à la Préfecture et de publication au Journal Officiel si elle a eu lieu ;
      - l'adresse du siège social ;
      - des informations sur les dirigeants.
      
      
      {:.fr-highlight}
      > Une association utilisatrice de votre démarche s'est aperçue que ses informations ne sont plus à jour ?
      > Vous pouvez l'orienter vers le [site officiel Le compte Asso](https://lecompteasso.associations.gouv.fr/declarer-un-changement-de-situation-de-mon-association/){:target="_blank"} où elle pourra déclarer son changement de situation.

  opening: public
  use_cases:
    - Marchés publics
    - Aides publiques
    - Préremplissage d'un formulaire
  use_cases_optional:
    - Détection de la fraude
  parameters:
    - Numéro de SIRET ou numéro RNA de l’association
