---
- uid: 'fabrique_numerique_ministeres_sociaux/conventions_collectives'
  path: '/v3/fabrique_numerique_ministeres_sociaux/etablissements/{siret}/conventions_collectives'
  position: 170
  perimeter:
    description: |+
      Des informations sur les conventions collectives sont également disponibles en [API publique et libre d'accès sur api.gouv.fr](https://api.gouv.fr/les-api/api-conventions-collectives){:target="_blank"}.
    entity_type_description: |+
      Cette API concerne les ✅ établissements **ayant déclaré des salariés** et ayant une convention.
      
      ❌ Les sociétés unipersonnelles dont le gérant est assimilé salarié ne sont pas concernées par cette API, même si la société en question est rattachée à une convention collective.
    updating_rules_description: |+
      L'actualisation des données de cette API est **ponctuelle et ne reflète pas forcément la réalité à jour de l'entreprise**.
      
      Cette API dépend de deux sources de données, dont la mise à jour est différente :  
      - la [liste des conventions collectives par entreprise, fournie par le Ministère du travail](https://www.data.gouv.fr/fr/datasets/liste-des-conventions-collectives-par-entreprise-siret/){:target="_blank"}, basée sur la Déclaration sociale nominative (DSN), est mise à jour ponctuellement avec plusieurs mois de retard ;
      - la [base KALI, fournie par la DILA](https://www.data.gouv.fr/fr/datasets/kali-conventions-collectives-nationales/){:target="_blank"}, permettant d'obtenir les textes des conventions collectives, est mise à jour quotidiennement à partir du Bulletin officiel « Conventions collectives ».
     
    entities:
      - associations
      - entreprises
  call_id: "SIRET"
  provider_uids:
    - 'fabsocial'
  data:
    description: |+
      Cette API délivre la **liste des différentes conventions** de l'établissement.

      Les caractéristiques suivantes sont transmises :
      - le titre, long et court de la convention ;
      - l'état de la convention, étendu ou non, c'est-à-dire si la convention est applicable à tous les employeurs de la branche ou uniquement aux signataires ;
      - l'identifiant IDCC, numéro à 4 chiffres ;
      - l'URL Légifrance du texte en vigueur.
  opening: public
  format:
    - Donnée structurée JSON 
  availability: 
    opening_time:
      7jours/7 et 24h/24 
  use_cases:
    - Marchés publics
    - Aides & subventions publiques
    - Détection de la fraude
  use_cases_optional:
    - Portail GRU - Pré-remplissage
    - Portail GRU - Instruction des démarches
  parameters:
    - Numéro de SIRET de l'établissement
  faq:
    - q: Quelles sont les sources de données de cette API ?
      a: |+
        Cette API est fournie par la fabrique numérique des ministères sociaux qui s'appuie sur plusieurs sources de données :
        - les données d'affiliation des établissements aux conventions sont issues de la DARES, direction d'études et statistiques du Ministère du Travail, publiées sur sur **[data.gouv.fr](https://www.data.gouv.fr/fr/datasets/liste-des-conventions-collectives-par-entreprise-siret/){:target="_blank"})** ;
        - Les informations relatives aux conventions collectives (numéro identifiant, titre, lien vers le texte légal, …) sont issues de la **base [KALI](https://www.data.gouv.fr/fr/datasets/kali-conventions-collectives-nationales/){:target="_blank"}** diffusée par la [DILA](https://www.dila.premier-ministre.gouv.fr/){:target="_blank"}, direction de l’information légale et administrative.
