---
- uid: 'urssaf/effectifs'
  position: 190
  path: '/v3/urssaf/effectifs'
  perimeter:
    entity_type_description: |+
      Cette API permet d’accéder aux effectifs de **✅ toutes les unités légales et établissements ayant des salariés**, à l’exception :
      - ❌ des entreprises des marins ;
      - ❌ des entreprises de cultes ;
      - ❌ des [junior-entreprises](https://fr.wikipedia.org/wiki/Junior-Entreprise){:target="_blank"} (environ 200).
      
      ✅ Les associations ayant un SIREN et des salariés sont concernées.
      ❌ Les administrations et collectivités territoriales ne sont pas concernées.
    geographical_scope_description: L'API délivre des informations sur les unités légales et établissements **✅établis en France à l'exception ❌ de Mayotte** (ce qui représente 3500 établissements manquants).
    updating_rules_description: Les effectifs mensuels sont mis à jour au mieux **le 15 de chaque mois pour le mois précédent**. C'est-à-dire que pour obtenir l'effectif du mois de février, il vous faut attendre _a minima_ le 15 mars.
    entities:
      - entreprises
      - associations
  opening: protected
  call_id: "SIREN"
  parameters:
    - Numéro de SIREN de l'unité légale ou numéro de SIRET de l'établissement
  format:
    - Donnée structurée JSON 
  availability: 
    opening_time:
      7jours/7 et 24h/24 
  use_cases:
    - Détection de la fraude
  use_cases_forbidden:
    - Marchés publics
    - Préremplissage d'un formulaire
  use_cases_optional:
    - Aides publiques
  provider_uids:
    - 'acoss'
  data:
    description: Cette API délivre les **effectifs mensuels** d'une unité légale ou d'un établisement ; et l'**effectif annuel** d'une unité légale.
  faq:
    - q: Comment sont calculés les effectifs ?
      a: |+
        Les effectifs sont calculés par la Caisse nationale de l'URSSAF. Le calcul des effectifs se fait en prenant en compte ✅ l’ensemble des contrats établis dans l’unité légale ou l'établissement, ❌ mis à part les : 
        - convention de stage ; 
        - contrat d’apprentissage ;
        - contrat de volontariat de service civique ; 
        - contrat d’initiative emploi ;
        - contrat d’accompagnement  ;
        - contrat de professionnalisation ;
        - contrat CDD en remplacement d’un salarié absent ; 
        - contrat CDD en remplacement d’un salarié en formation professionnelle ; 
        - contrat de soutien et d’aide par le travail ;  
        - ligne de service ;
        - mandat d’élu ;
        - fonctionnaire en détachement ;
        - vendeur à domicile indépendant ;
        - mandat social ;
        - contrat colporteurs de presse ;
        - voyageurs et représentants de commerce multi-carte ;
        - contrat collaborateur occasionnel du service public ;
        - militaires de réserve ;
        - parcours d’accès aux carrières (Pacte).

