---
- uid: 'insee/unites_legales'
  path: '/v3/insee/sirene/unites_legales/{siren}'
  perimeter:
    description: &insee_unites_legales_perimeter_description 
    "**Type de données :**
    \n
    \n
    Cette API délivre les informations de référence concernant les unités légales, diffusables commercialement, du répertoire Sirene.
    \n
    ⚠️ Elle ne concerne pas : 
    \n
    * les unités légales non diffusibles, appelables avec l'API `sirene/unites_legales/diffusibles` ;
    \n
    * les établissements, appelables avec les API `sirene/etablissements` et `sirene/etablissements/diffusibles`;
    \n
    * l'adresse de l'unité légale ou de ses établissements, appelables avec les API `/sirene/etablissements/:siret/adresse` et `/sirene/etablissements/diffusibles/:siret/adresse` ;
    \n
    * les mandataires sociaux, appelables avec l'API `infogreffe/mandataires_sociaux`.
    \n
    * les informations détaillées du siège social, appelables avec les API `unites_legales/diffusibles/:siren/siege_social` et `unites_legales/:siren/siege_social`.
    \n
    \n
    **Entreprises/associations concernées :**
    \n
    \n
    * Uniquement les unités dîtes "diffusibles", c'est à dire ayant donné leur accord pour que leurs informations soient publiques et utilisées à des fins commerciales.
    \n
    * ✅ les personnes morales de droit privé : les entreprises. Toutes les entreprises immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RCM) figurent dans la base Sirene ;
    \n
    * ✅ les personnes morales de droit public : les institutions et services de l’État et les collectivités territoriales ;
    \n
    * ✅ les entrepreneurs individuels exerçant de manière indépendante une profession non salariée (exemple : un commerçant, un médecin), ayant fait une déclaration d'activité.
    \n
    * ❌ Les particuliers employeurs ne font pas partie de la base Sirene ;
    \n
    * ✅ les associations ayant, en plus de leur numéro RNA, un numéro de SIREN/SIRET délivré lorsqu'elles :
    \n
    \t* emploient du personnel salarié ;
    \n
    \t* sont soumises à la TVA ;
    \n
    \t* ont demandé ou bénéficient de transferts financiers publics.
    \n
    * ✅ Les organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.
    \n
    \n
    **Périmètre géographique :**
    \n
    \n
    La base Sirene concerne les unités implantées en métropole, dans les DOM et dans les collectivités d'Outre-Mer de Saint Pierre et Miquelon, Saint Barthélémy et Saint Martin.
    \n
    \n
    ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l'État ou des communes est répertorié ; ❌ les entreprises ne sont donc pas disponibles.
    \n
    \n
    **Fraicheur de la donnée :**
    \n
    \n
    La mise a jour des données est faite quotidiennement entre 0h et 3h à l'INSEE.<br>
    \n
    \n
    **Pour en savoir plus :**
    \n
    \n
    [Contexte juridique du Répertoire National d’identification des entreprises et des établissements](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904)"
    entities:
    - entreprises_diffusibles
    - associations
  opening: protected
  call_id: &insee_unites_legales_call_id SIREN
  parameters: &insee_unites_legales_parameters
    - Numéro de SIREN de l'unité légale
  use_cases: &insee_unites_legales_use_cases
    - Aides publiques
    - Marchés publics
    - Préremplissage d'un formulaire
    - Détection de la fraude
  providers: &insee_unites_legales_providers
    - 'insee'

- uid: 'insee/unites_legales_diffusibles'
  path: '/v3/insee/sirene/unites_legales/diffusibles/{siren}'
  perimeter:
    description: *insee_unites_legales_perimeter_description
    entities:
    - entreprises
    - associations
  opening: public
  use_cases: *insee_unites_legales_use_cases
  parameters: *insee_unites_legales_parameters
  call_id: *insee_unites_legales_call_id
  providers: *insee_unites_legales_providers

