# Check https://github.com/betagouv/signup-back/tree/master/docs/webhooks.md for all events and their details
---
development: &development
  created: &created {}
  updated: &updated {}
  team_member_updated: &team_member_updated {}
  send_application: &send_application
    emails:
      - id: '11'
      - id: '12'
        when: 'in 14 days'
  notify: &notify {}
  review_application: &review_application {}
  refuse_application: &refuse_application
    emails:
      - id: '51'
        condition_on_authorization: 'user_first_name_is_run?'
      - id: '52'
        condition_on_authorization: 'user_last_name_is_run?'
        to:
          - 'authorization_request.contact_metier'
        cc:
          - 'authorization_request.contact_technique'
          - 'authorization_request.user'
  validate_application: &validate_application {}

  create: *created
  update: *updated
  team_member_update: *team_member_updated
  submit: *send_application
  request_changes: *review_application
  refuse: *refuse_application
  validate: *validate_application

test: *development

production: &production
  created: &created
    emails:
      - id: '3098214'
        when: 'in 14 days'
  updated: &updated {}
  team_member_updated: &team_member_updated {}
  send_application: &send_application
    emails:
      - id: '3098391'
      - id: '3098436'
        when: 'in 14 days'
  notify: &notify {}
  review_application: &review_application
    emails:
      - id: '3098236'
      - id: '3098155'
        when: 'in 14 days'
  refuse_application: &refuse_application
    emails:
      - id: '3084277'
  validate_application: &validate_application
    emails:
      - id: '4254728'
        condition_on_authorization: 'editor_authorization_request'
        to:
          - 'authorization_request.user'
        cc:
          - 'authorization_request.contact_technique'
          - 'authorization_request.contact_metier'

      - id: '3090261'
        condition_on_authorization: 'not_editor_and_all_contacts_have_the_same_email?'


      - id: '3090303'
        condition_on_authorization: 'not_editor_and_all_contacts_have_different_emails?'
        to:
          - 'authorization_request.user'
      - id: '3090321'
        condition_on_authorization: 'not_editor_and_all_contacts_have_different_emails?'
        to:
          - 'authorization_request.contact_technique'
        cc:
          - 'authorization_request.user'
      - id: '3084241'
        condition_on_authorization: 'not_editor_and_all_contacts_have_different_emails?'
        to:
          - 'authorization_request.contact_metier'
        cc:
          - 'authorization_request.user'
          - 'authorization_request.contact_technique'


      - id: '3090303'
        condition_on_authorization: 'not_editor_and_user_is_contact_metier_and_not_contact_technique?'
        to:
          - 'authorization_request.user'
      - id: '3090321'
        condition_on_authorization: 'not_editor_and_user_is_contact_metier_and_not_contact_technique?'
        to:
          - 'authorization_request.contact_technique'
        cc:
          - 'authorization_request.user'


      - id: '3090261'
        condition_on_authorization: 'not_editor_and_user_is_contact_technique_and_not_contact_metier?'
        to:
          - 'authorization_request.user'
      - id: '3084241'
        condition_on_authorization: 'not_editor_and_user_is_contact_technique_and_not_contact_metier?'
        to:
          - 'authorization_request.contact_metier'
        cc:
          - 'authorization_request.user'

      # EnquÃªte de satisfaction
      - id: '3251161'
        when: 'in 30 days'
        condition_on_authorization: 'not_editor_authorization_request'
        to:
          - 'authorization_request.user'

  create: *created
  update: *updated
  team_member_update: *team_member_updated
  submit: *send_application
  request_changes: *review_application
  refuse: *refuse_application
  validate: *validate_application

sandbox: *production
staging: *production
